

/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : Friday, November 12, 2010
	Important: Do not modify this file. Edit the file TradedHistoryTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using ETradeHistory.Entities;
using ETradeHistory.DataAccess;
using ETradeHistory.DataAccess.Bases;

#endregion

namespace ETradeHistory.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="TradedHistory"/> objects (entity, collection and repository).
    /// </summary>
   public partial class TradedHistoryTest
    {
    	// the TradedHistory instance used to test the repository.
		private TradedHistory mock;
		
		// the TList<TradedHistory> instance used to test the repository.
		private TList<TradedHistory> mockCollection;
		
		private static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadUncommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the TradedHistory Entity with the {0} --", ETradeHistory.DataAccess.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock TradedHistory entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.TradedHistoryProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.TradedHistoryProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all TradedHistory objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.TradedHistoryProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.TradedHistoryProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.TradedHistoryProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all TradedHistory children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.TradedHistoryProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.TradedHistoryProvider.DeepLoading += new EntityProviderBaseCore<TradedHistory, TradedHistoryKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.TradedHistoryProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("TradedHistory instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.TradedHistoryProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock TradedHistory entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				TradedHistory mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.TradedHistoryProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.TradedHistoryProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.TradedHistoryProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock TradedHistory entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (TradedHistory)CreateMockInstance(tm);
				DataRepository.TradedHistoryProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.TradedHistoryProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.TradedHistoryProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock TradedHistory entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_TradedHistory.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock TradedHistory entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_TradedHistory.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<TradedHistory>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a TradedHistory collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_TradedHistoryCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<TradedHistory> mockCollection = new TList<TradedHistory>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<TradedHistory> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a TradedHistory collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_TradedHistoryCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<TradedHistory>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<TradedHistory> mockCollection = (TList<TradedHistory>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<TradedHistory> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				TradedHistory entity = CreateMockInstance(tm);
				bool result = DataRepository.TradedHistoryProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				TradedHistory entity = CreateMockInstance(tm);
				bool result = DataRepository.TradedHistoryProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				TradedHistory t0 = DataRepository.TradedHistoryProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				TradedHistory entity = mock.Copy() as TradedHistory;
				entity = (TradedHistory)mock.Clone();
				Assert.IsTrue(TradedHistory.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				TradedHistory mock = CreateMockInstance(tm);
				bool result = DataRepository.TradedHistoryProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				TradedHistoryQuery query = new TradedHistoryQuery();
			
				query.AppendEquals(TradedHistoryColumn.TradeTime, mock.TradeTime.ToString());
				query.AppendEquals(TradedHistoryColumn.SubCustAccountId, mock.SubCustAccountId.ToString());
				if(mock.Type != null)
					query.AppendEquals(TradedHistoryColumn.Type, mock.Type.ToString());
				if(mock.FisOrderId != null)
					query.AppendEquals(TradedHistoryColumn.FisOrderId, mock.FisOrderId.ToString());
				query.AppendEquals(TradedHistoryColumn.SecSymbol, mock.SecSymbol.ToString());
				query.AppendEquals(TradedHistoryColumn.Side, mock.Side.ToString());
				query.AppendEquals(TradedHistoryColumn.Price, mock.Price.ToString());
				if(mock.ConPrice != null)
					query.AppendEquals(TradedHistoryColumn.ConPrice, mock.ConPrice.ToString());
				query.AppendEquals(TradedHistoryColumn.Volume, mock.Volume.ToString());
				if(mock.ExecutedVol != null)
					query.AppendEquals(TradedHistoryColumn.ExecutedVol, mock.ExecutedVol.ToString());
				if(mock.ExecutedPrice != null)
					query.AppendEquals(TradedHistoryColumn.ExecutedPrice, mock.ExecutedPrice.ToString());
				if(mock.CancelledVolume != null)
					query.AppendEquals(TradedHistoryColumn.CancelledVolume, mock.CancelledVolume.ToString());
				if(mock.MatchedTime != null)
					query.AppendEquals(TradedHistoryColumn.MatchedTime, mock.MatchedTime.ToString());
				if(mock.CancelledTime != null)
					query.AppendEquals(TradedHistoryColumn.CancelledTime, mock.CancelledTime.ToString());
				if(mock.OrdRejReason != null)
					query.AppendEquals(TradedHistoryColumn.OrdRejReason, mock.OrdRejReason.ToString());
				if(mock.CancelledRejReason != null)
					query.AppendEquals(TradedHistoryColumn.CancelledRejReason, mock.CancelledRejReason.ToString());
				if(mock.SourceId != null)
					query.AppendEquals(TradedHistoryColumn.SourceId, mock.SourceId.ToString());
				query.AppendEquals(TradedHistoryColumn.Market, mock.Market.ToString());
				if(mock.RefOrderId != null)
					query.AppendEquals(TradedHistoryColumn.RefOrderId, mock.RefOrderId.ToString());
				if(mock.EffDate != null)
					query.AppendEquals(TradedHistoryColumn.EffDate, mock.EffDate.ToString());
				if(mock.ExpDate != null)
					query.AppendEquals(TradedHistoryColumn.ExpDate, mock.ExpDate.ToString());
				if(mock.MinValue != null)
					query.AppendEquals(TradedHistoryColumn.MinValue, mock.MinValue.ToString());
				if(mock.MaxValue != null)
					query.AppendEquals(TradedHistoryColumn.MaxValue, mock.MaxValue.ToString());
				
				TList<TradedHistory> results = DataRepository.TradedHistoryProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed TradedHistory Entity with mock values.
		///</summary>
		static public TradedHistory CreateMockInstance_Generated(TransactionManager tm)
		{		
			TradedHistory mock = new TradedHistory();
						
			mock.TradeTime = TestUtility.Instance.RandomDateTime();
			mock.SubCustAccountId = TestUtility.Instance.RandomString(20, false);;
			mock.Type = TestUtility.Instance.RandomString(10, false);;
			mock.FisOrderId = TestUtility.Instance.RandomNumber();
			mock.SecSymbol = TestUtility.Instance.RandomString(8, false);;
			mock.Side = TestUtility.Instance.RandomString(1, false);;
			mock.Price = (decimal)TestUtility.Instance.RandomShort();
			mock.ConPrice = TestUtility.Instance.RandomString(1, false);;
			mock.Volume = (long)TestUtility.Instance.RandomNumber();
			mock.ExecutedVol = (long)TestUtility.Instance.RandomNumber();
			mock.ExecutedPrice = (decimal)TestUtility.Instance.RandomShort();
			mock.CancelledVolume = (long)TestUtility.Instance.RandomNumber();
			mock.MatchedTime = TestUtility.Instance.RandomDateTime();
			mock.CancelledTime = TestUtility.Instance.RandomDateTime();
			mock.OrdRejReason = TestUtility.Instance.RandomNumber();
			mock.CancelledRejReason = TestUtility.Instance.RandomNumber();
			mock.SourceId = TestUtility.Instance.RandomShort();
			mock.Market = TestUtility.Instance.RandomString(1, false);;
			mock.RefOrderId = TestUtility.Instance.RandomString(31, false);;
			mock.EffDate = TestUtility.Instance.RandomDateTime();
			mock.ExpDate = TestUtility.Instance.RandomDateTime();
			mock.MinValue = (decimal)TestUtility.Instance.RandomShort();
			mock.MaxValue = (decimal)TestUtility.Instance.RandomShort();
			
		
			// create a temporary collection and add the item to it
			TList<TradedHistory> tempMockCollection = new TList<TradedHistory>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (TradedHistory)mock;
		}
		
		
		///<summary>
		///  Update the Typed TradedHistory Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, TradedHistory mock)
		{
			mock.TradeTime = TestUtility.Instance.RandomDateTime();
			mock.SubCustAccountId = TestUtility.Instance.RandomString(20, false);;
			mock.Type = TestUtility.Instance.RandomString(10, false);;
			mock.FisOrderId = TestUtility.Instance.RandomNumber();
			mock.SecSymbol = TestUtility.Instance.RandomString(8, false);;
			mock.Side = TestUtility.Instance.RandomString(1, false);;
			mock.Price = (decimal)TestUtility.Instance.RandomShort();
			mock.ConPrice = TestUtility.Instance.RandomString(1, false);;
			mock.Volume = (long)TestUtility.Instance.RandomNumber();
			mock.ExecutedVol = (long)TestUtility.Instance.RandomNumber();
			mock.ExecutedPrice = (decimal)TestUtility.Instance.RandomShort();
			mock.CancelledVolume = (long)TestUtility.Instance.RandomNumber();
			mock.MatchedTime = TestUtility.Instance.RandomDateTime();
			mock.CancelledTime = TestUtility.Instance.RandomDateTime();
			mock.OrdRejReason = TestUtility.Instance.RandomNumber();
			mock.CancelledRejReason = TestUtility.Instance.RandomNumber();
			mock.SourceId = TestUtility.Instance.RandomShort();
			mock.Market = TestUtility.Instance.RandomString(1, false);;
			mock.RefOrderId = TestUtility.Instance.RandomString(31, false);;
			mock.EffDate = TestUtility.Instance.RandomDateTime();
			mock.ExpDate = TestUtility.Instance.RandomDateTime();
			mock.MinValue = (decimal)TestUtility.Instance.RandomShort();
			mock.MaxValue = (decimal)TestUtility.Instance.RandomShort();
			
		}
		#endregion
    }
}
