

/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, November 15, 2010
	Important: Do not modify this file. Edit the file QuickOrderTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using ETradeOrders.Entities;
using ETradeOrders.DataAccess;
using ETradeOrders.DataAccess.Bases;

#endregion

namespace ETradeOrders.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="QuickOrder"/> objects (entity, collection and repository).
    /// </summary>
   public partial class QuickOrderTest
    {
    	// the QuickOrder instance used to test the repository.
		private QuickOrder mock;
		
		// the TList<QuickOrder> instance used to test the repository.
		private TList<QuickOrder> mockCollection;
		
		private static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadUncommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the QuickOrder Entity with the {0} --", ETradeOrders.DataAccess.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock QuickOrder entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.QuickOrderProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.QuickOrderProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all QuickOrder objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.QuickOrderProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.QuickOrderProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.QuickOrderProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all QuickOrder children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.QuickOrderProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.QuickOrderProvider.DeepLoading += new EntityProviderBaseCore<QuickOrder, QuickOrderKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.QuickOrderProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("QuickOrder instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.QuickOrderProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock QuickOrder entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				QuickOrder mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.QuickOrderProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.QuickOrderProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.QuickOrderProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock QuickOrder entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (QuickOrder)CreateMockInstance(tm);
				DataRepository.QuickOrderProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.QuickOrderProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.QuickOrderProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock QuickOrder entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_QuickOrder.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock QuickOrder entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_QuickOrder.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<QuickOrder>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a QuickOrder collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_QuickOrderCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<QuickOrder> mockCollection = new TList<QuickOrder>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<QuickOrder> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a QuickOrder collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_QuickOrderCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<QuickOrder>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<QuickOrder> mockCollection = (TList<QuickOrder>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<QuickOrder> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				QuickOrder entity = CreateMockInstance(tm);
				bool result = DataRepository.QuickOrderProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				QuickOrder entity = CreateMockInstance(tm);
				bool result = DataRepository.QuickOrderProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				QuickOrder t0 = DataRepository.QuickOrderProvider.GetByQuickOrderId(tm, entity.QuickOrderId);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				QuickOrder entity = mock.Copy() as QuickOrder;
				entity = (QuickOrder)mock.Clone();
				Assert.IsTrue(QuickOrder.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				QuickOrder mock = CreateMockInstance(tm);
				bool result = DataRepository.QuickOrderProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				QuickOrderQuery query = new QuickOrderQuery();
			
				query.AppendEquals(QuickOrderColumn.SecSymbol, mock.SecSymbol.ToString());
				query.AppendEquals(QuickOrderColumn.Side, mock.Side.ToString());
				query.AppendEquals(QuickOrderColumn.Volume, mock.Volume.ToString());
				query.AppendEquals(QuickOrderColumn.SubCustAccountId, mock.SubCustAccountId.ToString());
				query.AppendEquals(QuickOrderColumn.Market, mock.Market.ToString());
				query.AppendEquals(QuickOrderColumn.TradeTime, mock.TradeTime.ToString());
				if(mock.TypeOfQuick != null)
					query.AppendEquals(QuickOrderColumn.TypeOfQuick, mock.TypeOfQuick.ToString());
				if(mock.Status != null)
					query.AppendEquals(QuickOrderColumn.Status, mock.Status.ToString());
				
				TList<QuickOrder> results = DataRepository.QuickOrderProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed QuickOrder Entity with mock values.
		///</summary>
		static public QuickOrder CreateMockInstance_Generated(TransactionManager tm)
		{		
			QuickOrder mock = new QuickOrder();
						
			mock.SecSymbol = TestUtility.Instance.RandomString(8, false);;
			mock.Side = TestUtility.Instance.RandomString(1, false);;
			mock.Volume = TestUtility.Instance.RandomNumber();
			mock.SubCustAccountId = TestUtility.Instance.RandomString(20, false);;
			mock.Market = TestUtility.Instance.RandomString(1, false);;
			mock.TradeTime = TestUtility.Instance.RandomDateTime();
			mock.TypeOfQuick = TestUtility.Instance.RandomShort();
			mock.Status = TestUtility.Instance.RandomString(1, false);;
			
		
			// create a temporary collection and add the item to it
			TList<QuickOrder> tempMockCollection = new TList<QuickOrder>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (QuickOrder)mock;
		}
		
		
		///<summary>
		///  Update the Typed QuickOrder Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, QuickOrder mock)
		{
			mock.SecSymbol = TestUtility.Instance.RandomString(8, false);;
			mock.Side = TestUtility.Instance.RandomString(1, false);;
			mock.Volume = TestUtility.Instance.RandomNumber();
			mock.SubCustAccountId = TestUtility.Instance.RandomString(20, false);;
			mock.Market = TestUtility.Instance.RandomString(1, false);;
			mock.TradeTime = TestUtility.Instance.RandomDateTime();
			mock.TypeOfQuick = TestUtility.Instance.RandomShort();
			mock.Status = TestUtility.Instance.RandomString(1, false);;
			
		}
		#endregion
    }
}
