
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, January 17, 2011
	Important: Do not modify this file. Edit the file StockTransfer.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Web.Script.Serialization;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using ETradeFinance.Entities.Validation;
#endregion

namespace ETradeFinance.Entities
{
	///<summary>
	/// An object representation of the 'StockTransfer' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class StockTransferBase : EntityBase, IStockTransfer, IEntityId<StockTransferKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private StockTransferEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private StockTransferEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private StockTransferEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<StockTransfer> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event StockTransferEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event StockTransferEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="StockTransferBase"/> instance.
		///</summary>
		public StockTransferBase()
		{
			this.entityData = new StockTransferEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="StockTransferBase"/> instance.
		///</summary>
		///<param name="_secSymbol">Ma co phieu chuyen</param>
		///<param name="_withdrawableAmt">Tong so luong CP co the rut/chuyen lay tu core</param>
		///<param name="_transferedAmt">Tong so luong CP da yeu cau chuyen(dang cho xu ly hoac dang xu ly)</param>
		///<param name="_advOrderAmt">Tong so luong CP da dat ban truoc chua khop (dang cho kich hoat, chua gui vao core)</param>
		///<param name="_avilableAmt">Tong so luong CP hien tai duoc phep chuyen</param>
		///<param name="_requestAmt">So luong CP khach hang yeu cau chuyen</param>
		///<param name="_requestTime">Thoi gian(ngay, gio) yeu cau chuyen co phieu</param>
		///<param name="_srcAccountId">Tai khoan nguon</param>
		///<param name="_destAccountId">Tai khoan dich</param>
		///<param name="_transType">Loai giao dich: chuyen, rut, khac</param>
		///<param name="_status">Trang thai cua yeu cau</param>
		///<param name="_execTime">Ngay gio xu ly</param>
		///<param name="_approvedAmt">So luong CP da duoc chap nhan</param>
		///<param name="_note">Ghi chu cua Broker</param>
		///<param name="_brokerId">Id c?a broker xu ly request.</param>
		public StockTransferBase(System.String _secSymbol, System.Int64? _withdrawableAmt, 
			System.Int64? _transferedAmt, System.Int64? _advOrderAmt, System.Int64? _avilableAmt, 
			System.Int64? _requestAmt, System.DateTime _requestTime, System.String _srcAccountId, 
			System.String _destAccountId, System.Int32? _transType, System.Int32? _status, System.DateTime? _execTime, 
			System.Int64? _approvedAmt, System.String _note, System.String _brokerId)
		{
			this.entityData = new StockTransferEntityData();
			this.backupData = null;

			this.SecSymbol = _secSymbol;
			this.WithdrawableAmt = _withdrawableAmt;
			this.TransferedAmt = _transferedAmt;
			this.AdvOrderAmt = _advOrderAmt;
			this.AvilableAmt = _avilableAmt;
			this.RequestAmt = _requestAmt;
			this.RequestTime = _requestTime;
			this.SrcAccountId = _srcAccountId;
			this.DestAccountId = _destAccountId;
			this.TransType = _transType;
			this.Status = _status;
			this.ExecTime = _execTime;
			this.ApprovedAmt = _approvedAmt;
			this.Note = _note;
			this.BrokerId = _brokerId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="StockTransfer"/> instance.
		///</summary>
		///<param name="_secSymbol">Ma co phieu chuyen</param>
		///<param name="_withdrawableAmt">Tong so luong CP co the rut/chuyen lay tu core</param>
		///<param name="_transferedAmt">Tong so luong CP da yeu cau chuyen(dang cho xu ly hoac dang xu ly)</param>
		///<param name="_advOrderAmt">Tong so luong CP da dat ban truoc chua khop (dang cho kich hoat, chua gui vao core)</param>
		///<param name="_avilableAmt">Tong so luong CP hien tai duoc phep chuyen</param>
		///<param name="_requestAmt">So luong CP khach hang yeu cau chuyen</param>
		///<param name="_requestTime">Thoi gian(ngay, gio) yeu cau chuyen co phieu</param>
		///<param name="_srcAccountId">Tai khoan nguon</param>
		///<param name="_destAccountId">Tai khoan dich</param>
		///<param name="_transType">Loai giao dich: chuyen, rut, khac</param>
		///<param name="_status">Trang thai cua yeu cau</param>
		///<param name="_execTime">Ngay gio xu ly</param>
		///<param name="_approvedAmt">So luong CP da duoc chap nhan</param>
		///<param name="_note">Ghi chu cua Broker</param>
		///<param name="_brokerId">Id c?a broker xu ly request.</param>
		public static StockTransfer CreateStockTransfer(System.String _secSymbol, System.Int64? _withdrawableAmt, 
			System.Int64? _transferedAmt, System.Int64? _advOrderAmt, System.Int64? _avilableAmt, 
			System.Int64? _requestAmt, System.DateTime _requestTime, System.String _srcAccountId, 
			System.String _destAccountId, System.Int32? _transType, System.Int32? _status, System.DateTime? _execTime, 
			System.Int64? _approvedAmt, System.String _note, System.String _brokerId)
		{
			StockTransfer newStockTransfer = new StockTransfer();
			newStockTransfer.SecSymbol = _secSymbol;
			newStockTransfer.WithdrawableAmt = _withdrawableAmt;
			newStockTransfer.TransferedAmt = _transferedAmt;
			newStockTransfer.AdvOrderAmt = _advOrderAmt;
			newStockTransfer.AvilableAmt = _avilableAmt;
			newStockTransfer.RequestAmt = _requestAmt;
			newStockTransfer.RequestTime = _requestTime;
			newStockTransfer.SrcAccountId = _srcAccountId;
			newStockTransfer.DestAccountId = _destAccountId;
			newStockTransfer.TransType = _transType;
			newStockTransfer.Status = _status;
			newStockTransfer.ExecTime = _execTime;
			newStockTransfer.ApprovedAmt = _approvedAmt;
			newStockTransfer.Note = _note;
			newStockTransfer.BrokerId = _brokerId;
			return newStockTransfer;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		StockTransferID identifies StockTransfer
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@"StockTransferID identifies StockTransfer"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
					
				OnColumnChanging(StockTransferColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SecSymbol property. 
		///		Ma co phieu chuyen
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"Ma co phieu chuyen"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 8)]
		public virtual System.String SecSymbol
		{
			get
			{
				return this.entityData.SecSymbol; 
			}
			
			set
			{
				if (this.entityData.SecSymbol == value)
					return;
					
				OnColumnChanging(StockTransferColumn.SecSymbol, this.entityData.SecSymbol);
				this.entityData.SecSymbol = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.SecSymbol, this.entityData.SecSymbol);
				OnPropertyChanged("SecSymbol");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the WithdrawableAmt property. 
		///		Tong so luong CP co the rut/chuyen lay tu core
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsWithdrawableAmtNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Tong so luong CP co the rut/chuyen lay tu core"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? WithdrawableAmt
		{
			get
			{
				return this.entityData.WithdrawableAmt; 
			}
			
			set
			{
				if (this.entityData.WithdrawableAmt == value)
					return;
					
				OnColumnChanging(StockTransferColumn.WithdrawableAmt, this.entityData.WithdrawableAmt);
				this.entityData.WithdrawableAmt = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.WithdrawableAmt, this.entityData.WithdrawableAmt);
				OnPropertyChanged("WithdrawableAmt");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TransferedAmt property. 
		///		Tong so luong CP da yeu cau chuyen(dang cho xu ly hoac dang xu ly)
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsTransferedAmtNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Tong so luong CP da yeu cau chuyen(dang cho xu ly hoac dang xu ly)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? TransferedAmt
		{
			get
			{
				return this.entityData.TransferedAmt; 
			}
			
			set
			{
				if (this.entityData.TransferedAmt == value)
					return;
					
				OnColumnChanging(StockTransferColumn.TransferedAmt, this.entityData.TransferedAmt);
				this.entityData.TransferedAmt = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.TransferedAmt, this.entityData.TransferedAmt);
				OnPropertyChanged("TransferedAmt");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AdvOrderAmt property. 
		///		Tong so luong CP da dat ban truoc chua khop (dang cho kich hoat, chua gui vao core)
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsAdvOrderAmtNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Tong so luong CP da dat ban truoc chua khop (dang cho kich hoat, chua gui vao core)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? AdvOrderAmt
		{
			get
			{
				return this.entityData.AdvOrderAmt; 
			}
			
			set
			{
				if (this.entityData.AdvOrderAmt == value)
					return;
					
				OnColumnChanging(StockTransferColumn.AdvOrderAmt, this.entityData.AdvOrderAmt);
				this.entityData.AdvOrderAmt = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.AdvOrderAmt, this.entityData.AdvOrderAmt);
				OnPropertyChanged("AdvOrderAmt");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AvilableAmt property. 
		///		Tong so luong CP hien tai duoc phep chuyen
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsAvilableAmtNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Tong so luong CP hien tai duoc phep chuyen"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? AvilableAmt
		{
			get
			{
				return this.entityData.AvilableAmt; 
			}
			
			set
			{
				if (this.entityData.AvilableAmt == value)
					return;
					
				OnColumnChanging(StockTransferColumn.AvilableAmt, this.entityData.AvilableAmt);
				this.entityData.AvilableAmt = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.AvilableAmt, this.entityData.AvilableAmt);
				OnPropertyChanged("AvilableAmt");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RequestAmt property. 
		///		So luong CP khach hang yeu cau chuyen
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsRequestAmtNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"So luong CP khach hang yeu cau chuyen"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? RequestAmt
		{
			get
			{
				return this.entityData.RequestAmt; 
			}
			
			set
			{
				if (this.entityData.RequestAmt == value)
					return;
					
				OnColumnChanging(StockTransferColumn.RequestAmt, this.entityData.RequestAmt);
				this.entityData.RequestAmt = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.RequestAmt, this.entityData.RequestAmt);
				OnPropertyChanged("RequestAmt");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RequestTime property. 
		///		Thoi gian(ngay, gio) yeu cau chuyen co phieu
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Thoi gian(ngay, gio) yeu cau chuyen co phieu"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime RequestTime
		{
			get
			{
				return this.entityData.RequestTime; 
			}
			
			set
			{
				if (this.entityData.RequestTime == value)
					return;
					
				OnColumnChanging(StockTransferColumn.RequestTime, this.entityData.RequestTime);
				this.entityData.RequestTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.RequestTime, this.entityData.RequestTime);
				OnPropertyChanged("RequestTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SrcAccountId property. 
		///		Tai khoan nguon
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"Tai khoan nguon"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 20)]
		public virtual System.String SrcAccountId
		{
			get
			{
				return this.entityData.SrcAccountId; 
			}
			
			set
			{
				if (this.entityData.SrcAccountId == value)
					return;
					
				OnColumnChanging(StockTransferColumn.SrcAccountId, this.entityData.SrcAccountId);
				this.entityData.SrcAccountId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.SrcAccountId, this.entityData.SrcAccountId);
				OnPropertyChanged("SrcAccountId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DestAccountId property. 
		///		Tai khoan dich
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"Tai khoan dich"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 20)]
		public virtual System.String DestAccountId
		{
			get
			{
				return this.entityData.DestAccountId; 
			}
			
			set
			{
				if (this.entityData.DestAccountId == value)
					return;
					
				OnColumnChanging(StockTransferColumn.DestAccountId, this.entityData.DestAccountId);
				this.entityData.DestAccountId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.DestAccountId, this.entityData.DestAccountId);
				OnPropertyChanged("DestAccountId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TransType property. 
		///		Loai giao dich: chuyen, rut, khac
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsTransTypeNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Loai giao dich: chuyen, rut, khac"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? TransType
		{
			get
			{
				return this.entityData.TransType; 
			}
			
			set
			{
				if (this.entityData.TransType == value)
					return;
					
				OnColumnChanging(StockTransferColumn.TransType, this.entityData.TransType);
				this.entityData.TransType = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.TransType, this.entityData.TransType);
				OnPropertyChanged("TransType");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		Trang thai cua yeu cau
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsStatusNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Trang thai cua yeu cau"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
					
				OnColumnChanging(StockTransferColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ExecTime property. 
		///		Ngay gio xu ly
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsExecTimeNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Ngay gio xu ly"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ExecTime
		{
			get
			{
				return this.entityData.ExecTime; 
			}
			
			set
			{
				if (this.entityData.ExecTime == value)
					return;
					
				OnColumnChanging(StockTransferColumn.ExecTime, this.entityData.ExecTime);
				this.entityData.ExecTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.ExecTime, this.entityData.ExecTime);
				OnPropertyChanged("ExecTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApprovedAmt property. 
		///		So luong CP da duoc chap nhan
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsApprovedAmtNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"So luong CP da duoc chap nhan"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? ApprovedAmt
		{
			get
			{
				return this.entityData.ApprovedAmt; 
			}
			
			set
			{
				if (this.entityData.ApprovedAmt == value)
					return;
					
				OnColumnChanging(StockTransferColumn.ApprovedAmt, this.entityData.ApprovedAmt);
				this.entityData.ApprovedAmt = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.ApprovedAmt, this.entityData.ApprovedAmt);
				OnPropertyChanged("ApprovedAmt");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Note property. 
		///		Ghi chu cua Broker
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Ghi chu cua Broker"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Note
		{
			get
			{
				return this.entityData.Note; 
			}
			
			set
			{
				if (this.entityData.Note == value)
					return;
					
				OnColumnChanging(StockTransferColumn.Note, this.entityData.Note);
				this.entityData.Note = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.Note, this.entityData.Note);
				OnPropertyChanged("Note");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the BrokerId property. 
		///		Id c?a broker xu ly request.
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Id c?a broker xu ly request."), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String BrokerId
		{
			get
			{
				return this.entityData.BrokerId; 
			}
			
			set
			{
				if (this.entityData.BrokerId == value)
					return;
					
				OnColumnChanging(StockTransferColumn.BrokerId, this.entityData.BrokerId);
				this.entityData.BrokerId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StockTransferColumn.BrokerId, this.entityData.BrokerId);
				OnPropertyChanged("BrokerId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("SecSymbol", "Sec Symbol"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SecSymbol", "Sec Symbol", 8));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("SrcAccountId", "Src Account Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SrcAccountId", "Src Account Id", 20));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("DestAccountId", "Dest Account Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("DestAccountId", "Dest Account Id", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("BrokerId", "Broker Id", 20));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public override string TableName
		{
			get { return "StockTransfer"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "SecSymbol", "WithdrawableAmt", "TransferedAmt", "AdvOrderAmt", "AvilableAmt", "RequestAmt", "RequestTime", "SrcAccountID", "DestAccountID", "TransType", "Status", "ExecTime", "ApprovedAmt", "Note", "BrokerID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as StockTransferEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (StockTransfer) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
        [ScriptIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<StockTransfer>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as StockTransfer);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed StockTransfer Entity 
		///</summary>
		protected virtual StockTransfer Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			StockTransfer copy = new StockTransfer();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.SecSymbol = this.SecSymbol;
				copy.WithdrawableAmt = this.WithdrawableAmt;
				copy.TransferedAmt = this.TransferedAmt;
				copy.AdvOrderAmt = this.AdvOrderAmt;
				copy.AvilableAmt = this.AvilableAmt;
				copy.RequestAmt = this.RequestAmt;
				copy.RequestTime = this.RequestTime;
				copy.SrcAccountId = this.SrcAccountId;
				copy.DestAccountId = this.DestAccountId;
				copy.TransType = this.TransType;
				copy.Status = this.Status;
				copy.ExecTime = this.ExecTime;
				copy.ApprovedAmt = this.ApprovedAmt;
				copy.Note = this.Note;
				copy.BrokerId = this.BrokerId;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed StockTransfer Entity 
		///</summary>
		public virtual StockTransfer Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed StockTransfer Entity which is a deep copy of the current entity.
		///</summary>
		public virtual StockTransfer DeepCopy()
		{
			return EntityHelper.Clone<StockTransfer>(this as StockTransfer);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as StockTransferEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new StockTransferEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as StockTransferEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(StockTransferColumn column)
		{
			switch(column)
			{
					case StockTransferColumn.Id:
					return entityData.Id != _originalData.Id;
					case StockTransferColumn.SecSymbol:
					return entityData.SecSymbol != _originalData.SecSymbol;
					case StockTransferColumn.WithdrawableAmt:
					return entityData.WithdrawableAmt != _originalData.WithdrawableAmt;
					case StockTransferColumn.TransferedAmt:
					return entityData.TransferedAmt != _originalData.TransferedAmt;
					case StockTransferColumn.AdvOrderAmt:
					return entityData.AdvOrderAmt != _originalData.AdvOrderAmt;
					case StockTransferColumn.AvilableAmt:
					return entityData.AvilableAmt != _originalData.AvilableAmt;
					case StockTransferColumn.RequestAmt:
					return entityData.RequestAmt != _originalData.RequestAmt;
					case StockTransferColumn.RequestTime:
					return entityData.RequestTime != _originalData.RequestTime;
					case StockTransferColumn.SrcAccountId:
					return entityData.SrcAccountId != _originalData.SrcAccountId;
					case StockTransferColumn.DestAccountId:
					return entityData.DestAccountId != _originalData.DestAccountId;
					case StockTransferColumn.TransType:
					return entityData.TransType != _originalData.TransType;
					case StockTransferColumn.Status:
					return entityData.Status != _originalData.Status;
					case StockTransferColumn.ExecTime:
					return entityData.ExecTime != _originalData.ExecTime;
					case StockTransferColumn.ApprovedAmt:
					return entityData.ApprovedAmt != _originalData.ApprovedAmt;
					case StockTransferColumn.Note:
					return entityData.Note != _originalData.Note;
					case StockTransferColumn.BrokerId:
					return entityData.BrokerId != _originalData.BrokerId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< StockTransferColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.SecSymbol != _originalData.SecSymbol;
			result = result || entityData.WithdrawableAmt != _originalData.WithdrawableAmt;
			result = result || entityData.TransferedAmt != _originalData.TransferedAmt;
			result = result || entityData.AdvOrderAmt != _originalData.AdvOrderAmt;
			result = result || entityData.AvilableAmt != _originalData.AvilableAmt;
			result = result || entityData.RequestAmt != _originalData.RequestAmt;
			result = result || entityData.RequestTime != _originalData.RequestTime;
			result = result || entityData.SrcAccountId != _originalData.SrcAccountId;
			result = result || entityData.DestAccountId != _originalData.DestAccountId;
			result = result || entityData.TransType != _originalData.TransType;
			result = result || entityData.Status != _originalData.Status;
			result = result || entityData.ExecTime != _originalData.ExecTime;
			result = result || entityData.ApprovedAmt != _originalData.ApprovedAmt;
			result = result || entityData.Note != _originalData.Note;
			result = result || entityData.BrokerId != _originalData.BrokerId;
			return result;
		}	
		
		///<summary>
		///  Returns a StockTransfer Entity with the original data.
		///</summary>
		public StockTransfer GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateStockTransfer(
				_originalData.SecSymbol,
				_originalData.WithdrawableAmt,
				_originalData.TransferedAmt,
				_originalData.AdvOrderAmt,
				_originalData.AvilableAmt,
				_originalData.RequestAmt,
				_originalData.RequestTime,
				_originalData.SrcAccountId,
				_originalData.DestAccountId,
				_originalData.TransType,
				_originalData.Status,
				_originalData.ExecTime,
				_originalData.ApprovedAmt,
				_originalData.Note,
				_originalData.BrokerId
				);
				
			return (StockTransfer)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="StockTransferBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is StockTransferBase)
				return ValueEquals(this, (StockTransferBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="StockTransferBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					this.SecSymbol.GetHashCode() ^ 
					((this.WithdrawableAmt == null) ? string.Empty : this.WithdrawableAmt.ToString()).GetHashCode() ^ 
					((this.TransferedAmt == null) ? string.Empty : this.TransferedAmt.ToString()).GetHashCode() ^ 
					((this.AdvOrderAmt == null) ? string.Empty : this.AdvOrderAmt.ToString()).GetHashCode() ^ 
					((this.AvilableAmt == null) ? string.Empty : this.AvilableAmt.ToString()).GetHashCode() ^ 
					((this.RequestAmt == null) ? string.Empty : this.RequestAmt.ToString()).GetHashCode() ^ 
					this.RequestTime.GetHashCode() ^ 
					this.SrcAccountId.GetHashCode() ^ 
					this.DestAccountId.GetHashCode() ^ 
					((this.TransType == null) ? string.Empty : this.TransType.ToString()).GetHashCode() ^ 
					((this.Status == null) ? string.Empty : this.Status.ToString()).GetHashCode() ^ 
					((this.ExecTime == null) ? string.Empty : this.ExecTime.ToString()).GetHashCode() ^ 
					((this.ApprovedAmt == null) ? string.Empty : this.ApprovedAmt.ToString()).GetHashCode() ^ 
					((this.Note == null) ? string.Empty : this.Note.ToString()).GetHashCode() ^ 
					((this.BrokerId == null) ? string.Empty : this.BrokerId.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="StockTransferBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(StockTransferBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="StockTransferBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="StockTransferBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="StockTransferBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(StockTransferBase Object1, StockTransferBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if (Object1.SecSymbol != Object2.SecSymbol)
				equal = false;
			if ( Object1.WithdrawableAmt != null && Object2.WithdrawableAmt != null )
			{
				if (Object1.WithdrawableAmt != Object2.WithdrawableAmt)
					equal = false;
			}
			else if (Object1.WithdrawableAmt == null ^ Object2.WithdrawableAmt == null )
			{
				equal = false;
			}
			if ( Object1.TransferedAmt != null && Object2.TransferedAmt != null )
			{
				if (Object1.TransferedAmt != Object2.TransferedAmt)
					equal = false;
			}
			else if (Object1.TransferedAmt == null ^ Object2.TransferedAmt == null )
			{
				equal = false;
			}
			if ( Object1.AdvOrderAmt != null && Object2.AdvOrderAmt != null )
			{
				if (Object1.AdvOrderAmt != Object2.AdvOrderAmt)
					equal = false;
			}
			else if (Object1.AdvOrderAmt == null ^ Object2.AdvOrderAmt == null )
			{
				equal = false;
			}
			if ( Object1.AvilableAmt != null && Object2.AvilableAmt != null )
			{
				if (Object1.AvilableAmt != Object2.AvilableAmt)
					equal = false;
			}
			else if (Object1.AvilableAmt == null ^ Object2.AvilableAmt == null )
			{
				equal = false;
			}
			if ( Object1.RequestAmt != null && Object2.RequestAmt != null )
			{
				if (Object1.RequestAmt != Object2.RequestAmt)
					equal = false;
			}
			else if (Object1.RequestAmt == null ^ Object2.RequestAmt == null )
			{
				equal = false;
			}
			if (Object1.RequestTime != Object2.RequestTime)
				equal = false;
			if (Object1.SrcAccountId != Object2.SrcAccountId)
				equal = false;
			if (Object1.DestAccountId != Object2.DestAccountId)
				equal = false;
			if ( Object1.TransType != null && Object2.TransType != null )
			{
				if (Object1.TransType != Object2.TransType)
					equal = false;
			}
			else if (Object1.TransType == null ^ Object2.TransType == null )
			{
				equal = false;
			}
			if ( Object1.Status != null && Object2.Status != null )
			{
				if (Object1.Status != Object2.Status)
					equal = false;
			}
			else if (Object1.Status == null ^ Object2.Status == null )
			{
				equal = false;
			}
			if ( Object1.ExecTime != null && Object2.ExecTime != null )
			{
				if (Object1.ExecTime != Object2.ExecTime)
					equal = false;
			}
			else if (Object1.ExecTime == null ^ Object2.ExecTime == null )
			{
				equal = false;
			}
			if ( Object1.ApprovedAmt != null && Object2.ApprovedAmt != null )
			{
				if (Object1.ApprovedAmt != Object2.ApprovedAmt)
					equal = false;
			}
			else if (Object1.ApprovedAmt == null ^ Object2.ApprovedAmt == null )
			{
				equal = false;
			}
			if ( Object1.Note != null && Object2.Note != null )
			{
				if (Object1.Note != Object2.Note)
					equal = false;
			}
			else if (Object1.Note == null ^ Object2.Note == null )
			{
				equal = false;
			}
			if ( Object1.BrokerId != null && Object2.BrokerId != null )
			{
				if (Object1.BrokerId != Object2.BrokerId)
					equal = false;
			}
			else if (Object1.BrokerId == null ^ Object2.BrokerId == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((StockTransferBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static StockTransferComparer GetComparer()
        {
            return new StockTransferComparer();
        }
        */

        // Comparer delegates back to StockTransfer
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(StockTransfer rhs, StockTransferColumn which)
        {
            switch (which)
            {
            	
            	
            	case StockTransferColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case StockTransferColumn.SecSymbol:
            		return this.SecSymbol.CompareTo(rhs.SecSymbol);
            		
            		                 
            	
            	
            	case StockTransferColumn.WithdrawableAmt:
            		return this.WithdrawableAmt.Value.CompareTo(rhs.WithdrawableAmt.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.TransferedAmt:
            		return this.TransferedAmt.Value.CompareTo(rhs.TransferedAmt.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.AdvOrderAmt:
            		return this.AdvOrderAmt.Value.CompareTo(rhs.AdvOrderAmt.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.AvilableAmt:
            		return this.AvilableAmt.Value.CompareTo(rhs.AvilableAmt.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.RequestAmt:
            		return this.RequestAmt.Value.CompareTo(rhs.RequestAmt.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.RequestTime:
            		return this.RequestTime.CompareTo(rhs.RequestTime);
            		
            		                 
            	
            	
            	case StockTransferColumn.SrcAccountId:
            		return this.SrcAccountId.CompareTo(rhs.SrcAccountId);
            		
            		                 
            	
            	
            	case StockTransferColumn.DestAccountId:
            		return this.DestAccountId.CompareTo(rhs.DestAccountId);
            		
            		                 
            	
            	
            	case StockTransferColumn.TransType:
            		return this.TransType.Value.CompareTo(rhs.TransType.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.Status:
            		return this.Status.Value.CompareTo(rhs.Status.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.ExecTime:
            		return this.ExecTime.Value.CompareTo(rhs.ExecTime.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.ApprovedAmt:
            		return this.ApprovedAmt.Value.CompareTo(rhs.ApprovedAmt.Value);
            		
            		                 
            	
            	
            	case StockTransferColumn.Note:
            		return this.Note.CompareTo(rhs.Note);
            		
            		                 
            	
            	
            	case StockTransferColumn.BrokerId:
            		return this.BrokerId.CompareTo(rhs.BrokerId);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
        [ScriptIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<StockTransferKey> Members
		
		// member variable for the EntityId property
		private StockTransferKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
        [ScriptIgnore]
		public virtual StockTransferKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new StockTransferKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute(), ScriptIgnore()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
        [ScriptIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("StockTransfer")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{17}{16}- Id: {0}{16}- SecSymbol: {1}{16}- WithdrawableAmt: {2}{16}- TransferedAmt: {3}{16}- AdvOrderAmt: {4}{16}- AvilableAmt: {5}{16}- RequestAmt: {6}{16}- RequestTime: {7}{16}- SrcAccountId: {8}{16}- DestAccountId: {9}{16}- TransType: {10}{16}- Status: {11}{16}- ExecTime: {12}{16}- ApprovedAmt: {13}{16}- Note: {14}{16}- BrokerId: {15}{16}{18}", 
				this.Id,
				this.SecSymbol,
				(this.WithdrawableAmt == null) ? string.Empty : this.WithdrawableAmt.ToString(),
				(this.TransferedAmt == null) ? string.Empty : this.TransferedAmt.ToString(),
				(this.AdvOrderAmt == null) ? string.Empty : this.AdvOrderAmt.ToString(),
				(this.AvilableAmt == null) ? string.Empty : this.AvilableAmt.ToString(),
				(this.RequestAmt == null) ? string.Empty : this.RequestAmt.ToString(),
				this.RequestTime,
				this.SrcAccountId,
				this.DestAccountId,
				(this.TransType == null) ? string.Empty : this.TransType.ToString(),
				(this.Status == null) ? string.Empty : this.Status.ToString(),
				(this.ExecTime == null) ? string.Empty : this.ExecTime.ToString(),
				(this.ApprovedAmt == null) ? string.Empty : this.ApprovedAmt.ToString(),
				(this.Note == null) ? string.Empty : this.Note.ToString(),
				(this.BrokerId == null) ? string.Empty : this.BrokerId.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'StockTransfer' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class StockTransferEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : StockTransferID identifies StockTransfer
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "StockTransfer"</remarks>
		public System.Int64 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// SecSymbol : Ma co phieu chuyen
		/// </summary>
		public System.String		  SecSymbol = string.Empty;
		
		/// <summary>
		/// WithdrawableAmt : Tong so luong CP co the rut/chuyen lay tu core
		/// </summary>
		public System.Int64?		  WithdrawableAmt = null;
		
		/// <summary>
		/// TransferedAmt : Tong so luong CP da yeu cau chuyen(dang cho xu ly hoac dang xu ly)
		/// </summary>
		public System.Int64?		  TransferedAmt = null;
		
		/// <summary>
		/// AdvOrderAmt : Tong so luong CP da dat ban truoc chua khop (dang cho kich hoat, chua gui vao core)
		/// </summary>
		public System.Int64?		  AdvOrderAmt = null;
		
		/// <summary>
		/// AvilableAmt : Tong so luong CP hien tai duoc phep chuyen
		/// </summary>
		public System.Int64?		  AvilableAmt = null;
		
		/// <summary>
		/// RequestAmt : So luong CP khach hang yeu cau chuyen
		/// </summary>
		public System.Int64?		  RequestAmt = null;
		
		/// <summary>
		/// RequestTime : Thoi gian(ngay, gio) yeu cau chuyen co phieu
		/// </summary>
		public System.DateTime		  RequestTime = DateTime.MinValue;
		
		/// <summary>
		/// SrcAccountID : Tai khoan nguon
		/// </summary>
		public System.String		  SrcAccountId = string.Empty;
		
		/// <summary>
		/// DestAccountID : Tai khoan dich
		/// </summary>
		public System.String		  DestAccountId = string.Empty;
		
		/// <summary>
		/// TransType : Loai giao dich: chuyen, rut, khac
		/// </summary>
		public System.Int32?		  TransType = null;
		
		/// <summary>
		/// Status : Trang thai cua yeu cau
		/// </summary>
		public System.Int32?		  Status = null;
		
		/// <summary>
		/// ExecTime : Ngay gio xu ly
		/// </summary>
		public System.DateTime?		  ExecTime = null;
		
		/// <summary>
		/// ApprovedAmt : So luong CP da duoc chap nhan
		/// </summary>
		public System.Int64?		  ApprovedAmt = null;
		
		/// <summary>
		/// Note : Ghi chu cua Broker
		/// </summary>
		public System.String		  Note = null;
		
		/// <summary>
		/// BrokerID : Id c?a broker xu ly request.
		/// </summary>
		public System.String		  BrokerId = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			StockTransferEntityData _tmp = new StockTransferEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.SecSymbol = this.SecSymbol;
			_tmp.WithdrawableAmt = this.WithdrawableAmt;
			_tmp.TransferedAmt = this.TransferedAmt;
			_tmp.AdvOrderAmt = this.AdvOrderAmt;
			_tmp.AvilableAmt = this.AvilableAmt;
			_tmp.RequestAmt = this.RequestAmt;
			_tmp.RequestTime = this.RequestTime;
			_tmp.SrcAccountId = this.SrcAccountId;
			_tmp.DestAccountId = this.DestAccountId;
			_tmp.TransType = this.TransType;
			_tmp.Status = this.Status;
			_tmp.ExecTime = this.ExecTime;
			_tmp.ApprovedAmt = this.ApprovedAmt;
			_tmp.Note = this.Note;
			_tmp.BrokerId = this.BrokerId;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			StockTransferEntityData _tmp = new StockTransferEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.SecSymbol = this.SecSymbol;
			_tmp.WithdrawableAmt = this.WithdrawableAmt;
			_tmp.TransferedAmt = this.TransferedAmt;
			_tmp.AdvOrderAmt = this.AdvOrderAmt;
			_tmp.AvilableAmt = this.AvilableAmt;
			_tmp.RequestAmt = this.RequestAmt;
			_tmp.RequestTime = this.RequestTime;
			_tmp.SrcAccountId = this.SrcAccountId;
			_tmp.DestAccountId = this.DestAccountId;
			_tmp.TransType = this.TransType;
			_tmp.Status = this.Status;
			_tmp.ExecTime = this.ExecTime;
			_tmp.ApprovedAmt = this.ApprovedAmt;
			_tmp.Note = this.Note;
			_tmp.BrokerId = this.BrokerId;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StockTransferColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(StockTransferColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StockTransferColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(StockTransferColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StockTransferColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(StockTransferColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				StockTransferEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new StockTransferEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StockTransferColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(StockTransferColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				StockTransferEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new StockTransferEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region StockTransferEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="StockTransfer"/> object.
	/// </remarks>
	public class StockTransferEventArgs : System.EventArgs
	{
		private StockTransferColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the StockTransferEventArgs class.
		///</summary>
		public StockTransferEventArgs(StockTransferColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the StockTransferEventArgs class.
		///</summary>
		public StockTransferEventArgs(StockTransferColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The StockTransferColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="StockTransferColumn" />
		public StockTransferColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all StockTransfer related events.
	///</summary>
	public delegate void StockTransferEventHandler(object sender, StockTransferEventArgs e);
	
	#region StockTransferComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class StockTransferComparer : System.Collections.Generic.IComparer<StockTransfer>
	{
		StockTransferColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:StockTransferComparer"/> class.
        /// </summary>
		public StockTransferComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:StockTransferComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public StockTransferComparer(StockTransferColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="StockTransfer"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="StockTransfer"/> to compare.</param>
        /// <param name="b">The second <c>StockTransfer</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(StockTransfer a, StockTransfer b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(StockTransfer entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(StockTransfer a, StockTransfer b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public StockTransferColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region StockTransferKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="StockTransfer"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class StockTransferKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the StockTransferKey class.
		/// </summary>
		public StockTransferKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the StockTransferKey class.
		/// </summary>
		public StockTransferKey(StockTransferBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the StockTransferKey class.
		/// </summary>
		public StockTransferKey(System.Int64 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private StockTransferBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public StockTransferBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int64 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int64 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["Id"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region StockTransferColumn Enum
	
	/// <summary>
	/// Enumerate the StockTransfer columns.
	/// </summary>
	[Serializable]
	public enum StockTransferColumn : int
	{
		/// <summary>
		/// Id : StockTransferID identifies StockTransfer
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		Id = 1,
		/// <summary>
		/// SecSymbol : Ma co phieu chuyen
		/// </summary>
		[EnumTextValue("SecSymbol")]
		[ColumnEnum("SecSymbol", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 8)]
		SecSymbol = 2,
		/// <summary>
		/// WithdrawableAmt : Tong so luong CP co the rut/chuyen lay tu core
		/// </summary>
		[EnumTextValue("WithdrawableAmt")]
		[ColumnEnum("WithdrawableAmt", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		WithdrawableAmt = 3,
		/// <summary>
		/// TransferedAmt : Tong so luong CP da yeu cau chuyen(dang cho xu ly hoac dang xu ly)
		/// </summary>
		[EnumTextValue("TransferedAmt")]
		[ColumnEnum("TransferedAmt", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		TransferedAmt = 4,
		/// <summary>
		/// AdvOrderAmt : Tong so luong CP da dat ban truoc chua khop (dang cho kich hoat, chua gui vao core)
		/// </summary>
		[EnumTextValue("AdvOrderAmt")]
		[ColumnEnum("AdvOrderAmt", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		AdvOrderAmt = 5,
		/// <summary>
		/// AvilableAmt : Tong so luong CP hien tai duoc phep chuyen
		/// </summary>
		[EnumTextValue("AvilableAmt")]
		[ColumnEnum("AvilableAmt", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		AvilableAmt = 6,
		/// <summary>
		/// RequestAmt : So luong CP khach hang yeu cau chuyen
		/// </summary>
		[EnumTextValue("RequestAmt")]
		[ColumnEnum("RequestAmt", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		RequestAmt = 7,
		/// <summary>
		/// RequestTime : Thoi gian(ngay, gio) yeu cau chuyen co phieu
		/// </summary>
		[EnumTextValue("RequestTime")]
		[ColumnEnum("RequestTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		RequestTime = 8,
		/// <summary>
		/// SrcAccountId : Tai khoan nguon
		/// </summary>
		[EnumTextValue("SrcAccountID")]
		[ColumnEnum("SrcAccountID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		SrcAccountId = 9,
		/// <summary>
		/// DestAccountId : Tai khoan dich
		/// </summary>
		[EnumTextValue("DestAccountID")]
		[ColumnEnum("DestAccountID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		DestAccountId = 10,
		/// <summary>
		/// TransType : Loai giao dich: chuyen, rut, khac
		/// </summary>
		[EnumTextValue("TransType")]
		[ColumnEnum("TransType", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		TransType = 11,
		/// <summary>
		/// Status : Trang thai cua yeu cau
		/// </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		Status = 12,
		/// <summary>
		/// ExecTime : Ngay gio xu ly
		/// </summary>
		[EnumTextValue("ExecTime")]
		[ColumnEnum("ExecTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ExecTime = 13,
		/// <summary>
		/// ApprovedAmt : So luong CP da duoc chap nhan
		/// </summary>
		[EnumTextValue("ApprovedAmt")]
		[ColumnEnum("ApprovedAmt", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		ApprovedAmt = 14,
		/// <summary>
		/// Note : Ghi chu cua Broker
		/// </summary>
		[EnumTextValue("Note")]
		[ColumnEnum("Note", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Note = 15,
		/// <summary>
		/// BrokerId : Id c?a broker xu ly request.
		/// </summary>
		[EnumTextValue("BrokerID")]
		[ColumnEnum("BrokerID", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		BrokerId = 16
	}//End enum

	#endregion StockTransferColumn Enum

} // end namespace
