//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPutOrder.StockCoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockCoreService.StockCoreServicesSoap")]
    public interface StockCoreServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short ReceiveOrder(long clientOrderID, string accountNo, string stockSymbol, long price, short volume, char side);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCashBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoPutOrder.StockCoreService.CashBalanceData GetCashBalance(string accountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockBalaceByAccNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoPutOrder.StockCoreService.StockBalanceData[] GetStockBalaceByAccNo(string accountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoPutOrder.StockCoreService.StockBalanceData GetStockAvailable(string accountNo, string stockSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockInfoCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoPutOrder.StockCoreService.StockInfoCache GetStockInfoCache(string symbol);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CashBalanceData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long withDrawField;
        
        private long buyCreditField;
        
        private long totalBuyField;
        
        private long totalSellField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long WithDraw {
            get {
                return this.withDrawField;
            }
            set {
                this.withDrawField = value;
                this.RaisePropertyChanged("WithDraw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long BuyCredit {
            get {
                return this.buyCreditField;
            }
            set {
                this.buyCreditField = value;
                this.RaisePropertyChanged("BuyCredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long TotalBuy {
            get {
                return this.totalBuyField;
            }
            set {
                this.totalBuyField = value;
                this.RaisePropertyChanged("TotalBuy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long TotalSell {
            get {
                return this.totalSellField;
            }
            set {
                this.totalSellField = value;
                this.RaisePropertyChanged("TotalSell");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockInfoCache : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte marketIDField;
        
        private string symbolField;
        
        private long floorField;
        
        private long ceilField;
        
        private int volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte MarketID {
            get {
                return this.marketIDField;
            }
            set {
                this.marketIDField = value;
                this.RaisePropertyChanged("MarketID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("Symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Ceil {
            get {
                return this.ceilField;
            }
            set {
                this.ceilField = value;
                this.RaisePropertyChanged("Ceil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("Volume");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockBalanceData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subCustAccountIDField;
        
        private string stockSymbolField;
        
        private long availableField;
        
        private long totalField;
        
        private long wTR_T1Field;
        
        private long wTR_T2Field;
        
        private long wTS_T1Field;
        
        private long wTS_T2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubCustAccountID {
            get {
                return this.subCustAccountIDField;
            }
            set {
                this.subCustAccountIDField = value;
                this.RaisePropertyChanged("SubCustAccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StockSymbol {
            get {
                return this.stockSymbolField;
            }
            set {
                this.stockSymbolField = value;
                this.RaisePropertyChanged("StockSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
                this.RaisePropertyChanged("Available");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long WTR_T1 {
            get {
                return this.wTR_T1Field;
            }
            set {
                this.wTR_T1Field = value;
                this.RaisePropertyChanged("WTR_T1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long WTR_T2 {
            get {
                return this.wTR_T2Field;
            }
            set {
                this.wTR_T2Field = value;
                this.RaisePropertyChanged("WTR_T2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long WTS_T1 {
            get {
                return this.wTS_T1Field;
            }
            set {
                this.wTS_T1Field = value;
                this.RaisePropertyChanged("WTS_T1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long WTS_T2 {
            get {
                return this.wTS_T2Field;
            }
            set {
                this.wTS_T2Field = value;
                this.RaisePropertyChanged("WTS_T2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockCoreServicesSoapChannel : AutoPutOrder.StockCoreService.StockCoreServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockCoreServicesSoapClient : System.ServiceModel.ClientBase<AutoPutOrder.StockCoreService.StockCoreServicesSoap>, AutoPutOrder.StockCoreService.StockCoreServicesSoap {
        
        public StockCoreServicesSoapClient() {
        }
        
        public StockCoreServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockCoreServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockCoreServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockCoreServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short ReceiveOrder(long clientOrderID, string accountNo, string stockSymbol, long price, short volume, char side) {
            return base.Channel.ReceiveOrder(clientOrderID, accountNo, stockSymbol, price, volume, side);
        }
        
        public AutoPutOrder.StockCoreService.CashBalanceData GetCashBalance(string accountNo) {
            return base.Channel.GetCashBalance(accountNo);
        }
        
        public AutoPutOrder.StockCoreService.StockBalanceData[] GetStockBalaceByAccNo(string accountNo) {
            return base.Channel.GetStockBalaceByAccNo(accountNo);
        }
        
        public AutoPutOrder.StockCoreService.StockBalanceData GetStockAvailable(string accountNo, string stockSymbol) {
            return base.Channel.GetStockAvailable(accountNo, stockSymbol);
        }
        
        public AutoPutOrder.StockCoreService.StockInfoCache GetStockInfoCache(string symbol) {
            return base.Channel.GetStockInfoCache(symbol);
        }
    }
}
