using System;
using System.ComponentModel;

namespace AccountManager.Entities
{
	/// <summary>
	///		The data structure representation of the 'BrokerPermission' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IBrokerPermission 
	{
		/// <summary>			
		/// BrokerID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "BrokerPermission"</remarks>
		System.String BrokerId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalBrokerId { get; set; }
			
		/// <summary>			
		/// PermissionID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "BrokerPermission"</remarks>
		System.Int32 PermissionId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalPermissionId { get; set; }
			
		
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


