
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Wednesday, July 13, 2011
	Important: Do not modify this file. Edit the file SmsCount.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Web.Script.Serialization;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AccountManager.Entities.Validation;
#endregion

namespace AccountManager.Entities
{
	///<summary>
	/// Count total of SMS sent	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class SmsCountBase : EntityBase, ISmsCount, IEntityId<SmsCountKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private SmsCountEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private SmsCountEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private SmsCountEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<SmsCount> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SmsCountEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SmsCountEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="SmsCountBase"/> instance.
		///</summary>
		public SmsCountBase()
		{
			this.entityData = new SmsCountEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="SmsCountBase"/> instance.
		///</summary>
		///<param name="_sendDate">SMS Sent date</param>
		///<param name="_total">Total of sms messages</param>
		public SmsCountBase(System.DateTime _sendDate, System.Int32 _total)
		{
			this.entityData = new SmsCountEntityData();
			this.backupData = null;

			this.SendDate = _sendDate;
			this.Total = _total;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="SmsCount"/> instance.
		///</summary>
		///<param name="_sendDate">SMS Sent date</param>
		///<param name="_total">Total of sms messages</param>
		public static SmsCount CreateSmsCount(System.DateTime _sendDate, System.Int32 _total)
		{
			SmsCount newSmsCount = new SmsCount();
			newSmsCount.SendDate = _sendDate;
			newSmsCount.Total = _total;
			return newSmsCount;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the SendDate property. 
		///		SMS Sent date
		/// </summary>
		/// <value>This type is smalldatetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"SMS Sent date"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.DateTime SendDate
		{
			get
			{
				return this.entityData.SendDate; 
			}
			
			set
			{
				if (this.entityData.SendDate == value)
					return;
					
				OnColumnChanging(SmsCountColumn.SendDate, this.entityData.SendDate);
				this.entityData.SendDate = value;
				this.EntityId.SendDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsCountColumn.SendDate, this.entityData.SendDate);
				OnPropertyChanged("SendDate");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the SendDate property.
		///		SMS Sent date
		/// </summary>
		/// <remarks>This is the original value of the SendDate property.</remarks>
		/// <value>This type is smalldatetime</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.DateTime OriginalSendDate
		{
			get { return this.entityData.OriginalSendDate; }
			set { this.entityData.OriginalSendDate = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Total property. 
		///		Total of sms messages
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Total of sms messages"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Total
		{
			get
			{
				return this.entityData.Total; 
			}
			
			set
			{
				if (this.entityData.Total == value)
					return;
					
				OnColumnChanging(SmsCountColumn.Total, this.entityData.Total);
				this.entityData.Total = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsCountColumn.Total, this.entityData.Total);
				OnPropertyChanged("Total");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public override string TableName
		{
			get { return "SMSCount"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"SendDate", "Total"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as SmsCountEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (SmsCount) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
        [ScriptIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<SmsCount>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as SmsCount);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed SmsCount Entity 
		///</summary>
		protected virtual SmsCount Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			SmsCount copy = new SmsCount();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.SendDate = this.SendDate;
					copy.OriginalSendDate = this.OriginalSendDate;
				copy.Total = this.Total;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed SmsCount Entity 
		///</summary>
		public virtual SmsCount Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed SmsCount Entity which is a deep copy of the current entity.
		///</summary>
		public virtual SmsCount DeepCopy()
		{
			return EntityHelper.Clone<SmsCount>(this as SmsCount);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as SmsCountEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new SmsCountEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as SmsCountEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(SmsCountColumn column)
		{
			switch(column)
			{
					case SmsCountColumn.SendDate:
					return entityData.SendDate != _originalData.SendDate;
					case SmsCountColumn.Total:
					return entityData.Total != _originalData.Total;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< SmsCountColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.SendDate != _originalData.SendDate;
			result = result || entityData.Total != _originalData.Total;
			return result;
		}	
		
		///<summary>
		///  Returns a SmsCount Entity with the original data.
		///</summary>
		public SmsCount GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateSmsCount(
				_originalData.SendDate,
				_originalData.Total
				);
				
			return (SmsCount)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="SmsCountBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is SmsCountBase)
				return ValueEquals(this, (SmsCountBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="SmsCountBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.SendDate.GetHashCode() ^ 
					this.Total.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="SmsCountBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(SmsCountBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="SmsCountBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="SmsCountBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="SmsCountBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(SmsCountBase Object1, SmsCountBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.SendDate != Object2.SendDate)
				equal = false;
			if (Object1.Total != Object2.Total)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((SmsCountBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static SmsCountComparer GetComparer()
        {
            return new SmsCountComparer();
        }
        */

        // Comparer delegates back to SmsCount
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(SmsCount rhs, SmsCountColumn which)
        {
            switch (which)
            {
            	
            	
            	case SmsCountColumn.SendDate:
            		return this.SendDate.CompareTo(rhs.SendDate);
            		
            		                 
            	
            	
            	case SmsCountColumn.Total:
            		return this.Total.CompareTo(rhs.Total);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
        [ScriptIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<SmsCountKey> Members
		
		// member variable for the EntityId property
		private SmsCountKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
        [ScriptIgnore]
		public virtual SmsCountKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new SmsCountKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute(), ScriptIgnore()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
        [ScriptIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("SmsCount")
					.Append("|").Append( this.SendDate.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{3}{2}- SendDate: {0}{2}- Total: {1}{2}{4}", 
				this.SendDate,
				this.Total,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'SMSCount' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class SmsCountEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// SendDate : SMS Sent date
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "SMSCount"</remarks>
		public System.DateTime SendDate;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.DateTime OriginalSendDate;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Total : Total of sms messages
		/// </summary>
		public System.Int32		  Total = (int)0;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			SmsCountEntityData _tmp = new SmsCountEntityData();
						
			_tmp.SendDate = this.SendDate;
			_tmp.OriginalSendDate = this.OriginalSendDate;
			
			_tmp.Total = this.Total;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			SmsCountEntityData _tmp = new SmsCountEntityData();
						
			_tmp.SendDate = this.SendDate;
			_tmp.OriginalSendDate = this.OriginalSendDate;
			
			_tmp.Total = this.Total;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsCountColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(SmsCountColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsCountColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(SmsCountColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsCountColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(SmsCountColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				SmsCountEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new SmsCountEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsCountColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(SmsCountColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				SmsCountEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new SmsCountEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region SmsCountEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="SmsCount"/> object.
	/// </remarks>
	public class SmsCountEventArgs : System.EventArgs
	{
		private SmsCountColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the SmsCountEventArgs class.
		///</summary>
		public SmsCountEventArgs(SmsCountColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the SmsCountEventArgs class.
		///</summary>
		public SmsCountEventArgs(SmsCountColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The SmsCountColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="SmsCountColumn" />
		public SmsCountColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all SmsCount related events.
	///</summary>
	public delegate void SmsCountEventHandler(object sender, SmsCountEventArgs e);
	
	#region SmsCountComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class SmsCountComparer : System.Collections.Generic.IComparer<SmsCount>
	{
		SmsCountColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:SmsCountComparer"/> class.
        /// </summary>
		public SmsCountComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:SmsCountComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public SmsCountComparer(SmsCountColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="SmsCount"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="SmsCount"/> to compare.</param>
        /// <param name="b">The second <c>SmsCount</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(SmsCount a, SmsCount b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(SmsCount entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(SmsCount a, SmsCount b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public SmsCountColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region SmsCountKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="SmsCount"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class SmsCountKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SmsCountKey class.
		/// </summary>
		public SmsCountKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the SmsCountKey class.
		/// </summary>
		public SmsCountKey(SmsCountBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.SendDate = entity.SendDate;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the SmsCountKey class.
		/// </summary>
		public SmsCountKey(System.DateTime _sendDate)
		{
			#region Init Properties

			this.SendDate = _sendDate;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private SmsCountBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public SmsCountBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the SendDate property
		private System.DateTime _sendDate;
		
		/// <summary>
		/// Gets or sets the SendDate property.
		/// </summary>
		public System.DateTime SendDate
		{
			get { return _sendDate; }
			set
			{
				if ( this.Entity != null )
					this.Entity.SendDate = value;
				
				_sendDate = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				SendDate = ( values["SendDate"] != null ) ? (System.DateTime) EntityUtil.ChangeType(values["SendDate"], typeof(System.DateTime)) : DateTime.MinValue;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("SendDate", SendDate);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("SendDate: {0}{1}",
								SendDate,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region SmsCountColumn Enum
	
	/// <summary>
	/// Enumerate the SmsCount columns.
	/// </summary>
	[Serializable]
	public enum SmsCountColumn : int
	{
		/// <summary>
		/// SendDate : SMS Sent date
		/// </summary>
		[EnumTextValue("SendDate")]
		[ColumnEnum("SendDate", typeof(System.DateTime), System.Data.DbType.DateTime, true, false, false)]
		SendDate = 1,
		/// <summary>
		/// Total : Total of sms messages
		/// </summary>
		[EnumTextValue("Total")]
		[ColumnEnum("Total", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Total = 2
	}//End enum

	#endregion SmsCountColumn Enum

} // end namespace
