using System;
using System.ComponentModel;

namespace RTStockData.Entities
{
	/// <summary>
	///		The data structure representation of the 'BasketInfo' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IBasketInfo 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "BasketInfo"</remarks>
		System.Int64 Id { get; set; }
				
		
		
		/// <summary>
		/// BasketId : 
		/// </summary>
		System.Decimal?  BasketId  { get; set; }
		
		/// <summary>
		/// IndexId : 
		/// </summary>
		System.Decimal?  IndexId  { get; set; }
		
		/// <summary>
		/// IndexCode : 
		/// </summary>
		System.String  IndexCode  { get; set; }
		
		/// <summary>
		/// StockCode : 
		/// </summary>
		System.String  StockCode  { get; set; }
		
		/// <summary>
		/// TotalCeilingQtty : 
		/// </summary>
		System.Decimal?  TotalCeilingQtty  { get; set; }
		
		/// <summary>
		/// AddDate : 
		/// </summary>
		System.DateTime?  AddDate  { get; set; }
		
		/// <summary>
		/// CurrentWeight : 
		/// </summary>
		System.Decimal?  CurrentWeight  { get; set; }
		
		/// <summary>
		/// TradeDate : 
		/// </summary>
		System.DateTime?  TradeDate  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


