using System;
using System.ComponentModel;

namespace RTStockData.Entities
{
	/// <summary>
	///		The data structure representation of the 'CompanyInfo' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICompanyInfo 
	{
		/// <summary>			
		/// CompanyId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CompanyInfo"</remarks>
		System.Int32 CompanyId { get; set; }
				
		
		
		/// <summary>
		/// Code : 
		/// </summary>
		System.String  Code  { get; set; }
		
		/// <summary>
		/// ShortName : 
		/// </summary>
		System.String  ShortName  { get; set; }
		
		/// <summary>
		/// Phone : 
		/// </summary>
		System.String  Phone  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// Fax : 
		/// </summary>
		System.String  Fax  { get; set; }
		
		/// <summary>
		/// Website : 
		/// </summary>
		System.String  Website  { get; set; }
		
		/// <summary>
		/// LastModified : 
		/// </summary>
		System.DateTime?  LastModified  { get; set; }
		
		/// <summary>
		/// IsPublished : 
		/// </summary>
		System.Boolean?  IsPublished  { get; set; }
		
		/// <summary>
		/// AuthorId : 
		/// </summary>
		System.Int32?  AuthorId  { get; set; }
		
		/// <summary>
		/// SectorId : 
		/// </summary>
		System.Guid?  SectorId  { get; set; }
		
		/// <summary>
		/// MarketId : 
		/// </summary>
		System.Int32  MarketId  { get; set; }
		
		/// <summary>
		/// PageView : 
		/// </summary>
		System.Int32?  PageView  { get; set; }
		
		/// <summary>
		/// IndustryGroup : 
		/// </summary>
		System.Int32?  IndustryGroup  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


