
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, January 17, 2011
	Important: Do not modify this file. Edit the file OddLotOrder.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Web.Script.Serialization;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using ETradeFinance.Entities.Validation;
#endregion

namespace ETradeFinance.Entities
{
	///<summary>
	/// An object representation of the 'OddLotOrder' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class OddLotOrderBase : EntityBase, IOddLotOrder, IEntityId<OddLotOrderKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private OddLotOrderEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private OddLotOrderEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private OddLotOrderEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<OddLotOrder> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event OddLotOrderEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event OddLotOrderEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="OddLotOrderBase"/> instance.
		///</summary>
		public OddLotOrderBase()
		{
			this.entityData = new OddLotOrderEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="OddLotOrderBase"/> instance.
		///</summary>
		///<param name="_secSymbol">Ma chung khoan</param>
		///<param name="_side">B = Mua, S = Ban</param>
		///<param name="_price">Gia chung khoan</param>
		///<param name="_volume">Khoi luong co phieu mua hay ban</param>
		///<param name="_subCustAccountId">Tai khoan thuc hien giao dich</param>
		///<param name="_market">Thi truong (O=HOSE, N=HNX, U=UPCOM)</param>
		///<param name="_execPrice">Gia da thuc hien ban</param>
		///<param name="_execVol">Kh?i lu?ng dã th?c hi?n</param>
		///<param name="_canceledVol">Khoi luong thuc hien huy</param>
		///<param name="_status">Trang thai cua request(dang cho, dang xu ly, da xu ly, huy boi nha dau tu, bi tu choi boi broker)</param>
		///<param name="_brokerId">ID c?a broker thuc hien ban</param>
		///<param name="_requestTime">Ngay gui yeu cau</param>
		///<param name="_execTime">Ngay xu ly</param>
		///<param name="_note">Ghi chú</param>
		public OddLotOrderBase(System.String _secSymbol, System.String _side, System.Decimal? _price, 
			System.Int64? _volume, System.String _subCustAccountId, System.String _market, System.Decimal? _execPrice, 
			System.Int64? _execVol, System.Int64? _canceledVol, System.Int32? _status, System.String _brokerId, 
			System.DateTime _requestTime, System.DateTime? _execTime, System.String _note)
		{
			this.entityData = new OddLotOrderEntityData();
			this.backupData = null;

			this.SecSymbol = _secSymbol;
			this.Side = _side;
			this.Price = _price;
			this.Volume = _volume;
			this.SubCustAccountId = _subCustAccountId;
			this.Market = _market;
			this.ExecPrice = _execPrice;
			this.ExecVol = _execVol;
			this.CanceledVol = _canceledVol;
			this.Status = _status;
			this.BrokerId = _brokerId;
			this.RequestTime = _requestTime;
			this.ExecTime = _execTime;
			this.Note = _note;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="OddLotOrder"/> instance.
		///</summary>
		///<param name="_secSymbol">Ma chung khoan</param>
		///<param name="_side">B = Mua, S = Ban</param>
		///<param name="_price">Gia chung khoan</param>
		///<param name="_volume">Khoi luong co phieu mua hay ban</param>
		///<param name="_subCustAccountId">Tai khoan thuc hien giao dich</param>
		///<param name="_market">Thi truong (O=HOSE, N=HNX, U=UPCOM)</param>
		///<param name="_execPrice">Gia da thuc hien ban</param>
		///<param name="_execVol">Kh?i lu?ng dã th?c hi?n</param>
		///<param name="_canceledVol">Khoi luong thuc hien huy</param>
		///<param name="_status">Trang thai cua request(dang cho, dang xu ly, da xu ly, huy boi nha dau tu, bi tu choi boi broker)</param>
		///<param name="_brokerId">ID c?a broker thuc hien ban</param>
		///<param name="_requestTime">Ngay gui yeu cau</param>
		///<param name="_execTime">Ngay xu ly</param>
		///<param name="_note">Ghi chú</param>
		public static OddLotOrder CreateOddLotOrder(System.String _secSymbol, System.String _side, System.Decimal? _price, 
			System.Int64? _volume, System.String _subCustAccountId, System.String _market, System.Decimal? _execPrice, 
			System.Int64? _execVol, System.Int64? _canceledVol, System.Int32? _status, System.String _brokerId, 
			System.DateTime _requestTime, System.DateTime? _execTime, System.String _note)
		{
			OddLotOrder newOddLotOrder = new OddLotOrder();
			newOddLotOrder.SecSymbol = _secSymbol;
			newOddLotOrder.Side = _side;
			newOddLotOrder.Price = _price;
			newOddLotOrder.Volume = _volume;
			newOddLotOrder.SubCustAccountId = _subCustAccountId;
			newOddLotOrder.Market = _market;
			newOddLotOrder.ExecPrice = _execPrice;
			newOddLotOrder.ExecVol = _execVol;
			newOddLotOrder.CanceledVol = _canceledVol;
			newOddLotOrder.Status = _status;
			newOddLotOrder.BrokerId = _brokerId;
			newOddLotOrder.RequestTime = _requestTime;
			newOddLotOrder.ExecTime = _execTime;
			newOddLotOrder.Note = _note;
			return newOddLotOrder;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		OddLotOrderID identifies OddLotOrder
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@"OddLotOrderID identifies OddLotOrder"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SecSymbol property. 
		///		Ma chung khoan
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"Ma chung khoan"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 8)]
		public virtual System.String SecSymbol
		{
			get
			{
				return this.entityData.SecSymbol; 
			}
			
			set
			{
				if (this.entityData.SecSymbol == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.SecSymbol, this.entityData.SecSymbol);
				this.entityData.SecSymbol = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.SecSymbol, this.entityData.SecSymbol);
				OnPropertyChanged("SecSymbol");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Side property. 
		///		B = Mua, S = Ban
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"B = Mua, S = Ban"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 1)]
		public virtual System.String Side
		{
			get
			{
				return this.entityData.Side; 
			}
			
			set
			{
				if (this.entityData.Side == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Side, this.entityData.Side);
				this.entityData.Side = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Side, this.entityData.Side);
				OnPropertyChanged("Side");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Price property. 
		///		Gia chung khoan
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsPriceNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Gia chung khoan"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? Price
		{
			get
			{
				return this.entityData.Price; 
			}
			
			set
			{
				if (this.entityData.Price == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Price, this.entityData.Price);
				this.entityData.Price = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Price, this.entityData.Price);
				OnPropertyChanged("Price");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Volume property. 
		///		Khoi luong co phieu mua hay ban
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsVolumeNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Khoi luong co phieu mua hay ban"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? Volume
		{
			get
			{
				return this.entityData.Volume; 
			}
			
			set
			{
				if (this.entityData.Volume == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Volume, this.entityData.Volume);
				this.entityData.Volume = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Volume, this.entityData.Volume);
				OnPropertyChanged("Volume");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SubCustAccountId property. 
		///		Tai khoan thuc hien giao dich
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"Tai khoan thuc hien giao dich"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 20)]
		public virtual System.String SubCustAccountId
		{
			get
			{
				return this.entityData.SubCustAccountId; 
			}
			
			set
			{
				if (this.entityData.SubCustAccountId == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.SubCustAccountId, this.entityData.SubCustAccountId);
				this.entityData.SubCustAccountId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.SubCustAccountId, this.entityData.SubCustAccountId);
				OnPropertyChanged("SubCustAccountId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Market property. 
		///		Thi truong (O=HOSE, N=HNX, U=UPCOM)
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@"Thi truong (O=HOSE, N=HNX, U=UPCOM)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 1)]
		public virtual System.String Market
		{
			get
			{
				return this.entityData.Market; 
			}
			
			set
			{
				if (this.entityData.Market == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Market, this.entityData.Market);
				this.entityData.Market = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Market, this.entityData.Market);
				OnPropertyChanged("Market");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ExecPrice property. 
		///		Gia da thuc hien ban
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsExecPriceNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Gia da thuc hien ban"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? ExecPrice
		{
			get
			{
				return this.entityData.ExecPrice; 
			}
			
			set
			{
				if (this.entityData.ExecPrice == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.ExecPrice, this.entityData.ExecPrice);
				this.entityData.ExecPrice = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.ExecPrice, this.entityData.ExecPrice);
				OnPropertyChanged("ExecPrice");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ExecVol property. 
		///		Kh?i lu?ng dã th?c hi?n
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsExecVolNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Kh?i lu?ng dã th?c hi?n"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? ExecVol
		{
			get
			{
				return this.entityData.ExecVol; 
			}
			
			set
			{
				if (this.entityData.ExecVol == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.ExecVol, this.entityData.ExecVol);
				this.entityData.ExecVol = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.ExecVol, this.entityData.ExecVol);
				OnPropertyChanged("ExecVol");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CanceledVol property. 
		///		Khoi luong thuc hien huy
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsCanceledVolNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Khoi luong thuc hien huy"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? CanceledVol
		{
			get
			{
				return this.entityData.CanceledVol; 
			}
			
			set
			{
				if (this.entityData.CanceledVol == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.CanceledVol, this.entityData.CanceledVol);
				this.entityData.CanceledVol = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.CanceledVol, this.entityData.CanceledVol);
				OnPropertyChanged("CanceledVol");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		Trang thai cua request(dang cho, dang xu ly, da xu ly, huy boi nha dau tu, bi tu choi boi broker)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsStatusNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Trang thai cua request(dang cho, dang xu ly, da xu ly, huy boi nha dau tu, bi tu choi boi broker)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the BrokerId property. 
		///		ID c?a broker thuc hien ban
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"ID c?a broker thuc hien ban"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String BrokerId
		{
			get
			{
				return this.entityData.BrokerId; 
			}
			
			set
			{
				if (this.entityData.BrokerId == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.BrokerId, this.entityData.BrokerId);
				this.entityData.BrokerId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.BrokerId, this.entityData.BrokerId);
				OnPropertyChanged("BrokerId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RequestTime property. 
		///		Ngay gui yeu cau
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Ngay gui yeu cau"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime RequestTime
		{
			get
			{
				return this.entityData.RequestTime; 
			}
			
			set
			{
				if (this.entityData.RequestTime == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.RequestTime, this.entityData.RequestTime);
				this.entityData.RequestTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.RequestTime, this.entityData.RequestTime);
				OnPropertyChanged("RequestTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ExecTime property. 
		///		Ngay xu ly
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsExecTimeNull() and perform business logic appropriately.
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Ngay xu ly"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ExecTime
		{
			get
			{
				return this.entityData.ExecTime; 
			}
			
			set
			{
				if (this.entityData.ExecTime == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.ExecTime, this.entityData.ExecTime);
				this.entityData.ExecTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.ExecTime, this.entityData.ExecTime);
				OnPropertyChanged("ExecTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Note property. 
		///		Ghi chú
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@"Ghi chú"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Note
		{
			get
			{
				return this.entityData.Note; 
			}
			
			set
			{
				if (this.entityData.Note == value)
					return;
					
				OnColumnChanging(OddLotOrderColumn.Note, this.entityData.Note);
				this.entityData.Note = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(OddLotOrderColumn.Note, this.entityData.Note);
				OnPropertyChanged("Note");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("SecSymbol", "Sec Symbol"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SecSymbol", "Sec Symbol", 8));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Side", "Side"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Side", "Side", 1));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("SubCustAccountId", "Sub Cust Account Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SubCustAccountId", "Sub Cust Account Id", 20));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Market", "Market"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Market", "Market", 1));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("BrokerId", "Broker Id", 20));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public override string TableName
		{
			get { return "OddLotOrder"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "SecSymbol", "Side", "Price", "Volume", "SubCustAccountID", "Market", "ExecPrice", "ExecVol", "CanceledVol", "Status", "BrokerID", "RequestTime", "ExecTime", "Note"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as OddLotOrderEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (OddLotOrder) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
        [ScriptIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<OddLotOrder>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as OddLotOrder);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed OddLotOrder Entity 
		///</summary>
		protected virtual OddLotOrder Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			OddLotOrder copy = new OddLotOrder();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.SecSymbol = this.SecSymbol;
				copy.Side = this.Side;
				copy.Price = this.Price;
				copy.Volume = this.Volume;
				copy.SubCustAccountId = this.SubCustAccountId;
				copy.Market = this.Market;
				copy.ExecPrice = this.ExecPrice;
				copy.ExecVol = this.ExecVol;
				copy.CanceledVol = this.CanceledVol;
				copy.Status = this.Status;
				copy.BrokerId = this.BrokerId;
				copy.RequestTime = this.RequestTime;
				copy.ExecTime = this.ExecTime;
				copy.Note = this.Note;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed OddLotOrder Entity 
		///</summary>
		public virtual OddLotOrder Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed OddLotOrder Entity which is a deep copy of the current entity.
		///</summary>
		public virtual OddLotOrder DeepCopy()
		{
			return EntityHelper.Clone<OddLotOrder>(this as OddLotOrder);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as OddLotOrderEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new OddLotOrderEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as OddLotOrderEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(OddLotOrderColumn column)
		{
			switch(column)
			{
					case OddLotOrderColumn.Id:
					return entityData.Id != _originalData.Id;
					case OddLotOrderColumn.SecSymbol:
					return entityData.SecSymbol != _originalData.SecSymbol;
					case OddLotOrderColumn.Side:
					return entityData.Side != _originalData.Side;
					case OddLotOrderColumn.Price:
					return entityData.Price != _originalData.Price;
					case OddLotOrderColumn.Volume:
					return entityData.Volume != _originalData.Volume;
					case OddLotOrderColumn.SubCustAccountId:
					return entityData.SubCustAccountId != _originalData.SubCustAccountId;
					case OddLotOrderColumn.Market:
					return entityData.Market != _originalData.Market;
					case OddLotOrderColumn.ExecPrice:
					return entityData.ExecPrice != _originalData.ExecPrice;
					case OddLotOrderColumn.ExecVol:
					return entityData.ExecVol != _originalData.ExecVol;
					case OddLotOrderColumn.CanceledVol:
					return entityData.CanceledVol != _originalData.CanceledVol;
					case OddLotOrderColumn.Status:
					return entityData.Status != _originalData.Status;
					case OddLotOrderColumn.BrokerId:
					return entityData.BrokerId != _originalData.BrokerId;
					case OddLotOrderColumn.RequestTime:
					return entityData.RequestTime != _originalData.RequestTime;
					case OddLotOrderColumn.ExecTime:
					return entityData.ExecTime != _originalData.ExecTime;
					case OddLotOrderColumn.Note:
					return entityData.Note != _originalData.Note;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< OddLotOrderColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.SecSymbol != _originalData.SecSymbol;
			result = result || entityData.Side != _originalData.Side;
			result = result || entityData.Price != _originalData.Price;
			result = result || entityData.Volume != _originalData.Volume;
			result = result || entityData.SubCustAccountId != _originalData.SubCustAccountId;
			result = result || entityData.Market != _originalData.Market;
			result = result || entityData.ExecPrice != _originalData.ExecPrice;
			result = result || entityData.ExecVol != _originalData.ExecVol;
			result = result || entityData.CanceledVol != _originalData.CanceledVol;
			result = result || entityData.Status != _originalData.Status;
			result = result || entityData.BrokerId != _originalData.BrokerId;
			result = result || entityData.RequestTime != _originalData.RequestTime;
			result = result || entityData.ExecTime != _originalData.ExecTime;
			result = result || entityData.Note != _originalData.Note;
			return result;
		}	
		
		///<summary>
		///  Returns a OddLotOrder Entity with the original data.
		///</summary>
		public OddLotOrder GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateOddLotOrder(
				_originalData.SecSymbol,
				_originalData.Side,
				_originalData.Price,
				_originalData.Volume,
				_originalData.SubCustAccountId,
				_originalData.Market,
				_originalData.ExecPrice,
				_originalData.ExecVol,
				_originalData.CanceledVol,
				_originalData.Status,
				_originalData.BrokerId,
				_originalData.RequestTime,
				_originalData.ExecTime,
				_originalData.Note
				);
				
			return (OddLotOrder)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="OddLotOrderBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is OddLotOrderBase)
				return ValueEquals(this, (OddLotOrderBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="OddLotOrderBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					this.SecSymbol.GetHashCode() ^ 
					this.Side.GetHashCode() ^ 
					((this.Price == null) ? string.Empty : this.Price.ToString()).GetHashCode() ^ 
					((this.Volume == null) ? string.Empty : this.Volume.ToString()).GetHashCode() ^ 
					this.SubCustAccountId.GetHashCode() ^ 
					this.Market.GetHashCode() ^ 
					((this.ExecPrice == null) ? string.Empty : this.ExecPrice.ToString()).GetHashCode() ^ 
					((this.ExecVol == null) ? string.Empty : this.ExecVol.ToString()).GetHashCode() ^ 
					((this.CanceledVol == null) ? string.Empty : this.CanceledVol.ToString()).GetHashCode() ^ 
					((this.Status == null) ? string.Empty : this.Status.ToString()).GetHashCode() ^ 
					((this.BrokerId == null) ? string.Empty : this.BrokerId.ToString()).GetHashCode() ^ 
					this.RequestTime.GetHashCode() ^ 
					((this.ExecTime == null) ? string.Empty : this.ExecTime.ToString()).GetHashCode() ^ 
					((this.Note == null) ? string.Empty : this.Note.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="OddLotOrderBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(OddLotOrderBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="OddLotOrderBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="OddLotOrderBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="OddLotOrderBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(OddLotOrderBase Object1, OddLotOrderBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if (Object1.SecSymbol != Object2.SecSymbol)
				equal = false;
			if (Object1.Side != Object2.Side)
				equal = false;
			if ( Object1.Price != null && Object2.Price != null )
			{
				if (Object1.Price != Object2.Price)
					equal = false;
			}
			else if (Object1.Price == null ^ Object2.Price == null )
			{
				equal = false;
			}
			if ( Object1.Volume != null && Object2.Volume != null )
			{
				if (Object1.Volume != Object2.Volume)
					equal = false;
			}
			else if (Object1.Volume == null ^ Object2.Volume == null )
			{
				equal = false;
			}
			if (Object1.SubCustAccountId != Object2.SubCustAccountId)
				equal = false;
			if (Object1.Market != Object2.Market)
				equal = false;
			if ( Object1.ExecPrice != null && Object2.ExecPrice != null )
			{
				if (Object1.ExecPrice != Object2.ExecPrice)
					equal = false;
			}
			else if (Object1.ExecPrice == null ^ Object2.ExecPrice == null )
			{
				equal = false;
			}
			if ( Object1.ExecVol != null && Object2.ExecVol != null )
			{
				if (Object1.ExecVol != Object2.ExecVol)
					equal = false;
			}
			else if (Object1.ExecVol == null ^ Object2.ExecVol == null )
			{
				equal = false;
			}
			if ( Object1.CanceledVol != null && Object2.CanceledVol != null )
			{
				if (Object1.CanceledVol != Object2.CanceledVol)
					equal = false;
			}
			else if (Object1.CanceledVol == null ^ Object2.CanceledVol == null )
			{
				equal = false;
			}
			if ( Object1.Status != null && Object2.Status != null )
			{
				if (Object1.Status != Object2.Status)
					equal = false;
			}
			else if (Object1.Status == null ^ Object2.Status == null )
			{
				equal = false;
			}
			if ( Object1.BrokerId != null && Object2.BrokerId != null )
			{
				if (Object1.BrokerId != Object2.BrokerId)
					equal = false;
			}
			else if (Object1.BrokerId == null ^ Object2.BrokerId == null )
			{
				equal = false;
			}
			if (Object1.RequestTime != Object2.RequestTime)
				equal = false;
			if ( Object1.ExecTime != null && Object2.ExecTime != null )
			{
				if (Object1.ExecTime != Object2.ExecTime)
					equal = false;
			}
			else if (Object1.ExecTime == null ^ Object2.ExecTime == null )
			{
				equal = false;
			}
			if ( Object1.Note != null && Object2.Note != null )
			{
				if (Object1.Note != Object2.Note)
					equal = false;
			}
			else if (Object1.Note == null ^ Object2.Note == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((OddLotOrderBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static OddLotOrderComparer GetComparer()
        {
            return new OddLotOrderComparer();
        }
        */

        // Comparer delegates back to OddLotOrder
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(OddLotOrder rhs, OddLotOrderColumn which)
        {
            switch (which)
            {
            	
            	
            	case OddLotOrderColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.SecSymbol:
            		return this.SecSymbol.CompareTo(rhs.SecSymbol);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.Side:
            		return this.Side.CompareTo(rhs.Side);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.Price:
            		return this.Price.Value.CompareTo(rhs.Price.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.Volume:
            		return this.Volume.Value.CompareTo(rhs.Volume.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.SubCustAccountId:
            		return this.SubCustAccountId.CompareTo(rhs.SubCustAccountId);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.Market:
            		return this.Market.CompareTo(rhs.Market);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.ExecPrice:
            		return this.ExecPrice.Value.CompareTo(rhs.ExecPrice.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.ExecVol:
            		return this.ExecVol.Value.CompareTo(rhs.ExecVol.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.CanceledVol:
            		return this.CanceledVol.Value.CompareTo(rhs.CanceledVol.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.Status:
            		return this.Status.Value.CompareTo(rhs.Status.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.BrokerId:
            		return this.BrokerId.CompareTo(rhs.BrokerId);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.RequestTime:
            		return this.RequestTime.CompareTo(rhs.RequestTime);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.ExecTime:
            		return this.ExecTime.Value.CompareTo(rhs.ExecTime.Value);
            		
            		                 
            	
            	
            	case OddLotOrderColumn.Note:
            		return this.Note.CompareTo(rhs.Note);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
        [ScriptIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<OddLotOrderKey> Members
		
		// member variable for the EntityId property
		private OddLotOrderKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
        [ScriptIgnore]
		public virtual OddLotOrderKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new OddLotOrderKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute(), ScriptIgnore()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
        [ScriptIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("OddLotOrder")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{16}{15}- Id: {0}{15}- SecSymbol: {1}{15}- Side: {2}{15}- Price: {3}{15}- Volume: {4}{15}- SubCustAccountId: {5}{15}- Market: {6}{15}- ExecPrice: {7}{15}- ExecVol: {8}{15}- CanceledVol: {9}{15}- Status: {10}{15}- BrokerId: {11}{15}- RequestTime: {12}{15}- ExecTime: {13}{15}- Note: {14}{15}{17}", 
				this.Id,
				this.SecSymbol,
				this.Side,
				(this.Price == null) ? string.Empty : this.Price.ToString(),
				(this.Volume == null) ? string.Empty : this.Volume.ToString(),
				this.SubCustAccountId,
				this.Market,
				(this.ExecPrice == null) ? string.Empty : this.ExecPrice.ToString(),
				(this.ExecVol == null) ? string.Empty : this.ExecVol.ToString(),
				(this.CanceledVol == null) ? string.Empty : this.CanceledVol.ToString(),
				(this.Status == null) ? string.Empty : this.Status.ToString(),
				(this.BrokerId == null) ? string.Empty : this.BrokerId.ToString(),
				this.RequestTime,
				(this.ExecTime == null) ? string.Empty : this.ExecTime.ToString(),
				(this.Note == null) ? string.Empty : this.Note.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'OddLotOrder' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class OddLotOrderEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : OddLotOrderID identifies OddLotOrder
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "OddLotOrder"</remarks>
		public System.Int64 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// SecSymbol : Ma chung khoan
		/// </summary>
		public System.String		  SecSymbol = string.Empty;
		
		/// <summary>
		/// Side : B = Mua, S = Ban
		/// </summary>
		public System.String		  Side = string.Empty;
		
		/// <summary>
		/// Price : Gia chung khoan
		/// </summary>
		public System.Decimal?		  Price = null;
		
		/// <summary>
		/// Volume : Khoi luong co phieu mua hay ban
		/// </summary>
		public System.Int64?		  Volume = null;
		
		/// <summary>
		/// SubCustAccountID : Tai khoan thuc hien giao dich
		/// </summary>
		public System.String		  SubCustAccountId = string.Empty;
		
		/// <summary>
		/// Market : Thi truong (O=HOSE, N=HNX, U=UPCOM)
		/// </summary>
		public System.String		  Market = string.Empty;
		
		/// <summary>
		/// ExecPrice : Gia da thuc hien ban
		/// </summary>
		public System.Decimal?		  ExecPrice = null;
		
		/// <summary>
		/// ExecVol : Kh?i lu?ng dã th?c hi?n
		/// </summary>
		public System.Int64?		  ExecVol = null;
		
		/// <summary>
		/// CanceledVol : Khoi luong thuc hien huy
		/// </summary>
		public System.Int64?		  CanceledVol = null;
		
		/// <summary>
		/// Status : Trang thai cua request(dang cho, dang xu ly, da xu ly, huy boi nha dau tu, bi tu choi boi broker)
		/// </summary>
		public System.Int32?		  Status = null;
		
		/// <summary>
		/// BrokerID : ID c?a broker thuc hien ban
		/// </summary>
		public System.String		  BrokerId = null;
		
		/// <summary>
		/// RequestTime : Ngay gui yeu cau
		/// </summary>
		public System.DateTime		  RequestTime = DateTime.MinValue;
		
		/// <summary>
		/// ExecTime : Ngay xu ly
		/// </summary>
		public System.DateTime?		  ExecTime = null;
		
		/// <summary>
		/// Note : Ghi chú
		/// </summary>
		public System.String		  Note = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			OddLotOrderEntityData _tmp = new OddLotOrderEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.SecSymbol = this.SecSymbol;
			_tmp.Side = this.Side;
			_tmp.Price = this.Price;
			_tmp.Volume = this.Volume;
			_tmp.SubCustAccountId = this.SubCustAccountId;
			_tmp.Market = this.Market;
			_tmp.ExecPrice = this.ExecPrice;
			_tmp.ExecVol = this.ExecVol;
			_tmp.CanceledVol = this.CanceledVol;
			_tmp.Status = this.Status;
			_tmp.BrokerId = this.BrokerId;
			_tmp.RequestTime = this.RequestTime;
			_tmp.ExecTime = this.ExecTime;
			_tmp.Note = this.Note;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			OddLotOrderEntityData _tmp = new OddLotOrderEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.SecSymbol = this.SecSymbol;
			_tmp.Side = this.Side;
			_tmp.Price = this.Price;
			_tmp.Volume = this.Volume;
			_tmp.SubCustAccountId = this.SubCustAccountId;
			_tmp.Market = this.Market;
			_tmp.ExecPrice = this.ExecPrice;
			_tmp.ExecVol = this.ExecVol;
			_tmp.CanceledVol = this.CanceledVol;
			_tmp.Status = this.Status;
			_tmp.BrokerId = this.BrokerId;
			_tmp.RequestTime = this.RequestTime;
			_tmp.ExecTime = this.ExecTime;
			_tmp.Note = this.Note;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute(), ScriptIgnore()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OddLotOrderColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(OddLotOrderColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OddLotOrderColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(OddLotOrderColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OddLotOrderColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(OddLotOrderColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				OddLotOrderEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new OddLotOrderEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="OddLotOrderColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(OddLotOrderColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				OddLotOrderEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new OddLotOrderEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region OddLotOrderEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="OddLotOrder"/> object.
	/// </remarks>
	public class OddLotOrderEventArgs : System.EventArgs
	{
		private OddLotOrderColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the OddLotOrderEventArgs class.
		///</summary>
		public OddLotOrderEventArgs(OddLotOrderColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the OddLotOrderEventArgs class.
		///</summary>
		public OddLotOrderEventArgs(OddLotOrderColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The OddLotOrderColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="OddLotOrderColumn" />
		public OddLotOrderColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all OddLotOrder related events.
	///</summary>
	public delegate void OddLotOrderEventHandler(object sender, OddLotOrderEventArgs e);
	
	#region OddLotOrderComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class OddLotOrderComparer : System.Collections.Generic.IComparer<OddLotOrder>
	{
		OddLotOrderColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:OddLotOrderComparer"/> class.
        /// </summary>
		public OddLotOrderComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:OddLotOrderComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public OddLotOrderComparer(OddLotOrderColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="OddLotOrder"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="OddLotOrder"/> to compare.</param>
        /// <param name="b">The second <c>OddLotOrder</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(OddLotOrder a, OddLotOrder b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(OddLotOrder entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(OddLotOrder a, OddLotOrder b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public OddLotOrderColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region OddLotOrderKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="OddLotOrder"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class OddLotOrderKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the OddLotOrderKey class.
		/// </summary>
		public OddLotOrderKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the OddLotOrderKey class.
		/// </summary>
		public OddLotOrderKey(OddLotOrderBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the OddLotOrderKey class.
		/// </summary>
		public OddLotOrderKey(System.Int64 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private OddLotOrderBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public OddLotOrderBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int64 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int64 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["Id"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region OddLotOrderColumn Enum
	
	/// <summary>
	/// Enumerate the OddLotOrder columns.
	/// </summary>
	[Serializable]
	public enum OddLotOrderColumn : int
	{
		/// <summary>
		/// Id : OddLotOrderID identifies OddLotOrder
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		Id = 1,
		/// <summary>
		/// SecSymbol : Ma chung khoan
		/// </summary>
		[EnumTextValue("SecSymbol")]
		[ColumnEnum("SecSymbol", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 8)]
		SecSymbol = 2,
		/// <summary>
		/// Side : B = Mua, S = Ban
		/// </summary>
		[EnumTextValue("Side")]
		[ColumnEnum("Side", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 1)]
		Side = 3,
		/// <summary>
		/// Price : Gia chung khoan
		/// </summary>
		[EnumTextValue("Price")]
		[ColumnEnum("Price", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		Price = 4,
		/// <summary>
		/// Volume : Khoi luong co phieu mua hay ban
		/// </summary>
		[EnumTextValue("Volume")]
		[ColumnEnum("Volume", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		Volume = 5,
		/// <summary>
		/// SubCustAccountId : Tai khoan thuc hien giao dich
		/// </summary>
		[EnumTextValue("SubCustAccountID")]
		[ColumnEnum("SubCustAccountID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		SubCustAccountId = 6,
		/// <summary>
		/// Market : Thi truong (O=HOSE, N=HNX, U=UPCOM)
		/// </summary>
		[EnumTextValue("Market")]
		[ColumnEnum("Market", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 1)]
		Market = 7,
		/// <summary>
		/// ExecPrice : Gia da thuc hien ban
		/// </summary>
		[EnumTextValue("ExecPrice")]
		[ColumnEnum("ExecPrice", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		ExecPrice = 8,
		/// <summary>
		/// ExecVol : Kh?i lu?ng dã th?c hi?n
		/// </summary>
		[EnumTextValue("ExecVol")]
		[ColumnEnum("ExecVol", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		ExecVol = 9,
		/// <summary>
		/// CanceledVol : Khoi luong thuc hien huy
		/// </summary>
		[EnumTextValue("CanceledVol")]
		[ColumnEnum("CanceledVol", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		CanceledVol = 10,
		/// <summary>
		/// Status : Trang thai cua request(dang cho, dang xu ly, da xu ly, huy boi nha dau tu, bi tu choi boi broker)
		/// </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		Status = 11,
		/// <summary>
		/// BrokerId : ID c?a broker thuc hien ban
		/// </summary>
		[EnumTextValue("BrokerID")]
		[ColumnEnum("BrokerID", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		BrokerId = 12,
		/// <summary>
		/// RequestTime : Ngay gui yeu cau
		/// </summary>
		[EnumTextValue("RequestTime")]
		[ColumnEnum("RequestTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		RequestTime = 13,
		/// <summary>
		/// ExecTime : Ngay xu ly
		/// </summary>
		[EnumTextValue("ExecTime")]
		[ColumnEnum("ExecTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ExecTime = 14,
		/// <summary>
		/// Note : Ghi chú
		/// </summary>
		[EnumTextValue("Note")]
		[ColumnEnum("Note", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Note = 15
	}//End enum

	#endregion OddLotOrderColumn Enum

} // end namespace
