//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.32559.
// 
#pragma warning disable 1591

namespace ETradeCommon.StockCoreServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StockCoreServicesSoap", Namespace="http://tempuri.org/")]
    public partial class StockCoreServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReceiveOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCashBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockBalaceByAccNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockAvailableOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockInfoCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StockCoreServices() {
            this.Url = global::ETradeCommon.Properties.Settings.Default.ETradeCommon_StockCoreServices_StockCoreServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReceiveOrderCompletedEventHandler ReceiveOrderCompleted;
        
        /// <remarks/>
        public event GetCashBalanceCompletedEventHandler GetCashBalanceCompleted;
        
        /// <remarks/>
        public event GetStockBalaceByAccNoCompletedEventHandler GetStockBalaceByAccNoCompleted;
        
        /// <remarks/>
        public event GetStockAvailableCompletedEventHandler GetStockAvailableCompleted;
        
        /// <remarks/>
        public event GetStockInfoCacheCompletedEventHandler GetStockInfoCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public short ReceiveOrder(long clientOrderID, string accountNo, string stockSymbol, long price, short volume, char side) {
            object[] results = this.Invoke("ReceiveOrder", new object[] {
                        clientOrderID,
                        accountNo,
                        stockSymbol,
                        price,
                        volume,
                        side});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveOrderAsync(long clientOrderID, string accountNo, string stockSymbol, long price, short volume, char side) {
            this.ReceiveOrderAsync(clientOrderID, accountNo, stockSymbol, price, volume, side, null);
        }
        
        /// <remarks/>
        public void ReceiveOrderAsync(long clientOrderID, string accountNo, string stockSymbol, long price, short volume, char side, object userState) {
            if ((this.ReceiveOrderOperationCompleted == null)) {
                this.ReceiveOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveOrderOperationCompleted);
            }
            this.InvokeAsync("ReceiveOrder", new object[] {
                        clientOrderID,
                        accountNo,
                        stockSymbol,
                        price,
                        volume,
                        side}, this.ReceiveOrderOperationCompleted, userState);
        }
        
        private void OnReceiveOrderOperationCompleted(object arg) {
            if ((this.ReceiveOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveOrderCompleted(this, new ReceiveOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCashBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CashBalanceData GetCashBalance(string accountNo) {
            object[] results = this.Invoke("GetCashBalance", new object[] {
                        accountNo});
            return ((CashBalanceData)(results[0]));
        }
        
        /// <remarks/>
        public void GetCashBalanceAsync(string accountNo) {
            this.GetCashBalanceAsync(accountNo, null);
        }
        
        /// <remarks/>
        public void GetCashBalanceAsync(string accountNo, object userState) {
            if ((this.GetCashBalanceOperationCompleted == null)) {
                this.GetCashBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCashBalanceOperationCompleted);
            }
            this.InvokeAsync("GetCashBalance", new object[] {
                        accountNo}, this.GetCashBalanceOperationCompleted, userState);
        }
        
        private void OnGetCashBalanceOperationCompleted(object arg) {
            if ((this.GetCashBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCashBalanceCompleted(this, new GetCashBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockBalaceByAccNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockBalanceData[] GetStockBalaceByAccNo(string accountNo) {
            object[] results = this.Invoke("GetStockBalaceByAccNo", new object[] {
                        accountNo});
            return ((StockBalanceData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockBalaceByAccNoAsync(string accountNo) {
            this.GetStockBalaceByAccNoAsync(accountNo, null);
        }
        
        /// <remarks/>
        public void GetStockBalaceByAccNoAsync(string accountNo, object userState) {
            if ((this.GetStockBalaceByAccNoOperationCompleted == null)) {
                this.GetStockBalaceByAccNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockBalaceByAccNoOperationCompleted);
            }
            this.InvokeAsync("GetStockBalaceByAccNo", new object[] {
                        accountNo}, this.GetStockBalaceByAccNoOperationCompleted, userState);
        }
        
        private void OnGetStockBalaceByAccNoOperationCompleted(object arg) {
            if ((this.GetStockBalaceByAccNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockBalaceByAccNoCompleted(this, new GetStockBalaceByAccNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockAvailable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockBalanceData GetStockAvailable(string accountNo, string stockSymbol) {
            object[] results = this.Invoke("GetStockAvailable", new object[] {
                        accountNo,
                        stockSymbol});
            return ((StockBalanceData)(results[0]));
        }
        
        /// <remarks/>
        public void GetStockAvailableAsync(string accountNo, string stockSymbol) {
            this.GetStockAvailableAsync(accountNo, stockSymbol, null);
        }
        
        /// <remarks/>
        public void GetStockAvailableAsync(string accountNo, string stockSymbol, object userState) {
            if ((this.GetStockAvailableOperationCompleted == null)) {
                this.GetStockAvailableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockAvailableOperationCompleted);
            }
            this.InvokeAsync("GetStockAvailable", new object[] {
                        accountNo,
                        stockSymbol}, this.GetStockAvailableOperationCompleted, userState);
        }
        
        private void OnGetStockAvailableOperationCompleted(object arg) {
            if ((this.GetStockAvailableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockAvailableCompleted(this, new GetStockAvailableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockInfoCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockInfoCache GetStockInfoCache(string symbol) {
            object[] results = this.Invoke("GetStockInfoCache", new object[] {
                        symbol});
            return ((StockInfoCache)(results[0]));
        }
        
        /// <remarks/>
        public void GetStockInfoCacheAsync(string symbol) {
            this.GetStockInfoCacheAsync(symbol, null);
        }
        
        /// <remarks/>
        public void GetStockInfoCacheAsync(string symbol, object userState) {
            if ((this.GetStockInfoCacheOperationCompleted == null)) {
                this.GetStockInfoCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockInfoCacheOperationCompleted);
            }
            this.InvokeAsync("GetStockInfoCache", new object[] {
                        symbol}, this.GetStockInfoCacheOperationCompleted, userState);
        }
        
        private void OnGetStockInfoCacheOperationCompleted(object arg) {
            if ((this.GetStockInfoCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockInfoCacheCompleted(this, new GetStockInfoCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.32559")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CashBalanceData {
        
        private long withDrawField;
        
        private long buyCreditField;
        
        private long totalBuyField;
        
        private long totalSellField;
        
        /// <remarks/>
        public long WithDraw {
            get {
                return this.withDrawField;
            }
            set {
                this.withDrawField = value;
            }
        }
        
        /// <remarks/>
        public long BuyCredit {
            get {
                return this.buyCreditField;
            }
            set {
                this.buyCreditField = value;
            }
        }
        
        /// <remarks/>
        public long TotalBuy {
            get {
                return this.totalBuyField;
            }
            set {
                this.totalBuyField = value;
            }
        }
        
        /// <remarks/>
        public long TotalSell {
            get {
                return this.totalSellField;
            }
            set {
                this.totalSellField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.32559")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockInfoCache {
        
        private byte marketIDField;
        
        private string symbolField;
        
        private long floorField;
        
        private long ceilField;
        
        private int volumeField;
        
        /// <remarks/>
        public byte MarketID {
            get {
                return this.marketIDField;
            }
            set {
                this.marketIDField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public long Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        public long Ceil {
            get {
                return this.ceilField;
            }
            set {
                this.ceilField = value;
            }
        }
        
        /// <remarks/>
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.32559")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockBalanceData {
        
        private string subCustAccountIDField;
        
        private string stockSymbolField;
        
        private long availableField;
        
        private long totalField;
        
        private long wTR_T1Field;
        
        private long wTR_T2Field;
        
        private long wTS_T1Field;
        
        private long wTS_T2Field;
        
        /// <remarks/>
        public string SubCustAccountID {
            get {
                return this.subCustAccountIDField;
            }
            set {
                this.subCustAccountIDField = value;
            }
        }
        
        /// <remarks/>
        public string StockSymbol {
            get {
                return this.stockSymbolField;
            }
            set {
                this.stockSymbolField = value;
            }
        }
        
        /// <remarks/>
        public long Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        /// <remarks/>
        public long Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public long WTR_T1 {
            get {
                return this.wTR_T1Field;
            }
            set {
                this.wTR_T1Field = value;
            }
        }
        
        /// <remarks/>
        public long WTR_T2 {
            get {
                return this.wTR_T2Field;
            }
            set {
                this.wTR_T2Field = value;
            }
        }
        
        /// <remarks/>
        public long WTS_T1 {
            get {
                return this.wTS_T1Field;
            }
            set {
                this.wTS_T1Field = value;
            }
        }
        
        /// <remarks/>
        public long WTS_T2 {
            get {
                return this.wTS_T2Field;
            }
            set {
                this.wTS_T2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void ReceiveOrderCompletedEventHandler(object sender, ReceiveOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void GetCashBalanceCompletedEventHandler(object sender, GetCashBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCashBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCashBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CashBalanceData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CashBalanceData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void GetStockBalaceByAccNoCompletedEventHandler(object sender, GetStockBalaceByAccNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockBalaceByAccNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockBalaceByAccNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockBalanceData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockBalanceData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void GetStockAvailableCompletedEventHandler(object sender, GetStockAvailableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockAvailableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockAvailableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockBalanceData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockBalanceData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void GetStockInfoCacheCompletedEventHandler(object sender, GetStockInfoCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockInfoCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockInfoCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockInfoCache Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockInfoCache)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591